// GENERATED by tool/gen_bridge_raw.py from engine/bridge/include/bw_bridge.h. Do not edit.
// ignore_for_file: non_constant_identifier_names, constant_identifier_names

// dart:ffi implementation of BridgeRaw (Linux desktop now, Android later).

import 'dart:ffi' as ffi;
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'bridge_raw.dart';

class BridgeRawFfi extends BridgeRaw {
  final String libraryPath;
  final ffi.DynamicLibrary _lib;

  BridgeRawFfi(this.libraryPath) : _lib = ffi.DynamicLibrary.open(libraryPath);

  /// Next to the executable when bundled (linux/CMakeLists.txt installs it
  /// into the bundle's lib/), otherwise the bridge's own build output.
  static String defaultLibraryPath() {
    // Android loads it from the APK's native libraries by name.
    if (Platform.isAndroid) return 'libbwbridge.so';
    final exeDir = File(Platform.resolvedExecutable).parent.path;
    final bundled = '$exeDir/lib/libbwbridge.so';
    if (File(bundled).existsSync()) return bundled;
    return '${Directory.current.path}/engine/bridge/build/libbwbridge.so';
  }

  @override
  int malloc(int size) => calloc<ffi.Uint8>(size <= 0 ? 1 : size).address;

  @override
  void free(int address) => calloc.free(ffi.Pointer<ffi.Uint8>.fromAddress(address));

  @override
  Uint8List bytes(int address, int length) => ffi.Pointer<ffi.Uint8>.fromAddress(address).asTypedList(length);

  @override
  Future<int> replayCommands(int bridge, Int32List log, int endFrame) {
    final path = libraryPath;
    return Isolate.run(() {
      final raw = BridgeRawFfi(path);
      final buf = raw.malloc(log.isEmpty ? 4 : log.lengthInBytes);
      try {
        raw.bytes(buf, log.lengthInBytes).setAll(0, log.buffer.asUint8List(log.offsetInBytes, log.lengthInBytes));
        return raw.bw_bridge_replay_commands(bridge, buf, log.length, endFrame);
      } finally {
        raw.free(buf);
      }
    });
  }

  late final _bw_bridge_abi_version = _lib.lookupFunction<ffi.Int32 Function(), int Function()>('bw_bridge_abi_version');
  @override
  int bw_bridge_abi_version() => _bw_bridge_abi_version();

  late final _bw_bridge_create = _lib.lookupFunction<ffi.IntPtr Function(), int Function()>('bw_bridge_create');
  @override
  int bw_bridge_create() => _bw_bridge_create();

  late final _bw_bridge_destroy = _lib.lookupFunction<ffi.Void Function(ffi.IntPtr), void Function(int)>('bw_bridge_destroy');
  @override
  void bw_bridge_destroy(int bridge) => _bw_bridge_destroy(bridge);

  late final _bw_bridge_load_assets = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr), int Function(int, int)>('bw_bridge_load_assets');
  @override
  int bw_bridge_load_assets(int bridge, int data_dir) => _bw_bridge_load_assets(bridge, data_dir);

  late final _bw_bridge_new_melee_game = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_new_melee_game');
  @override
  int bw_bridge_new_melee_game(int bridge, int map_file, int my_player_slot, int my_race) => _bw_bridge_new_melee_game(bridge, map_file, my_player_slot, my_race);

  late final _bw_bridge_new_game = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int)>('bw_bridge_new_game');
  @override
  int bw_bridge_new_game(int bridge, int map_file, int setup, int out_slots) => _bw_bridge_new_game(bridge, map_file, setup, out_slots);

  late final _bw_bridge_step = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_step');
  @override
  int bw_bridge_step(int bridge, int n_frames) => _bw_bridge_step(bridge, n_frames);

  late final _bw_bridge_victory_state = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_victory_state');
  @override
  int bw_bridge_victory_state(int bridge, int player_slot) => _bw_bridge_victory_state(bridge, player_slot);

  late final _bw_bridge_alliances = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliances');
  @override
  int bw_bridge_alliances(int bridge, int out, int max_count) => _bw_bridge_alliances(bridge, out, max_count);

  late final _bw_bridge_alliance_set_open = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_set_open');
  @override
  int bw_bridge_alliance_set_open(int bridge, int player_slot, int open) => _bw_bridge_alliance_set_open(bridge, player_slot, open);

  late final _bw_bridge_alliance_set_share = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_set_share');
  @override
  int bw_bridge_alliance_set_share(int bridge, int player_slot, int on) => _bw_bridge_alliance_set_share(bridge, player_slot, on);

  late final _bw_bridge_alliance_get_share = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_alliance_get_share');
  @override
  int bw_bridge_alliance_get_share(int bridge, int player_slot) => _bw_bridge_alliance_get_share(bridge, player_slot);

  late final _bw_bridge_alliance_set_defensive = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_set_defensive');
  @override
  int bw_bridge_alliance_set_defensive(int bridge, int player_slot, int on) => _bw_bridge_alliance_set_defensive(bridge, player_slot, on);

  late final _bw_bridge_alliance_get_defensive = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_alliance_get_defensive');
  @override
  int bw_bridge_alliance_get_defensive(int bridge, int player_slot) => _bw_bridge_alliance_get_defensive(bridge, player_slot);

  late final _bw_bridge_alliance_kick = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_kick');
  @override
  int bw_bridge_alliance_kick(int bridge, int by, int target) => _bw_bridge_alliance_kick(bridge, by, target);

  late final _bw_bridge_alliance_set_capped = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_alliance_set_capped');
  @override
  int bw_bridge_alliance_set_capped(int bridge, int on) => _bw_bridge_alliance_set_capped(bridge, on);

  late final _bw_bridge_alliance_invite = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_invite');
  @override
  int bw_bridge_alliance_invite(int bridge, int from, int to) => _bw_bridge_alliance_invite(bridge, from, to);

  late final _bw_bridge_alliance_respond = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_alliance_respond');
  @override
  int bw_bridge_alliance_respond(int bridge, int player_slot, int from, int accept) => _bw_bridge_alliance_respond(bridge, player_slot, from, accept);

  late final _bw_bridge_alliance_leave = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_alliance_leave');
  @override
  int bw_bridge_alliance_leave(int bridge, int player_slot) => _bw_bridge_alliance_leave(bridge, player_slot);

  late final _bw_bridge_alliance_surrender = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_alliance_surrender');
  @override
  int bw_bridge_alliance_surrender(int bridge, int from, int to) => _bw_bridge_alliance_surrender(bridge, from, to);

  late final _bw_bridge_alliance_answer_surrender = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_alliance_answer_surrender');
  @override
  int bw_bridge_alliance_answer_surrender(int bridge, int player_slot, int from, int accept) => _bw_bridge_alliance_answer_surrender(bridge, player_slot, from, accept);

  late final _bw_bridge_player_stats = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_player_stats');
  @override
  int bw_bridge_player_stats(int bridge, int player_slot, int out) => _bw_bridge_player_stats(bridge, player_slot, out);

  late final _bw_bridge_poll_alliance_events = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_poll_alliance_events');
  @override
  int bw_bridge_poll_alliance_events(int bridge, int out, int max_count) => _bw_bridge_poll_alliance_events(bridge, out, max_count);

  late final _bw_bridge_set_autoplay = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_set_autoplay');
  @override
  int bw_bridge_set_autoplay(int bridge, int player_slot, int modes) => _bw_bridge_set_autoplay(bridge, player_slot, modes);

  late final _bw_bridge_get_autoplay = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_get_autoplay');
  @override
  int bw_bridge_get_autoplay(int bridge, int player_slot) => _bw_bridge_get_autoplay(bridge, player_slot);

  late final _bw_bridge_set_viewer = _lib.lookupFunction<ffi.Void Function(ffi.IntPtr, ffi.Int32), void Function(int, int)>('bw_bridge_set_viewer');
  @override
  void bw_bridge_set_viewer(int bridge, int player_slot) => _bw_bridge_set_viewer(bridge, player_slot);

  late final _bw_bridge_get_fog = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_fog');
  @override
  int bw_bridge_get_fog(int bridge, int player_slot, int out_tiles, int out_cap) => _bw_bridge_get_fog(bridge, player_slot, out_tiles, out_cap);

  late final _bw_bridge_explore_map = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_explore_map');
  @override
  int bw_bridge_explore_map(int bridge, int player_slot) => _bw_bridge_explore_map(bridge, player_slot);

  late final _bw_bridge_set_legacy_unit_ids = _lib.lookupFunction<ffi.Void Function(ffi.IntPtr, ffi.Int32), void Function(int, int)>('bw_bridge_set_legacy_unit_ids');
  @override
  void bw_bridge_set_legacy_unit_ids(int bridge, int on) => _bw_bridge_set_legacy_unit_ids(bridge, on);

  late final _bw_bridge_command_log = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_command_log');
  @override
  int bw_bridge_command_log(int bridge, int out, int out_cap) => _bw_bridge_command_log(bridge, out, out_cap);

  late final _bw_bridge_set_deferred = _lib.lookupFunction<ffi.Void Function(ffi.IntPtr, ffi.Int32), void Function(int, int)>('bw_bridge_set_deferred');
  @override
  void bw_bridge_set_deferred(int bridge, int on) => _bw_bridge_set_deferred(bridge, on);

  late final _bw_bridge_take_outbox = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_take_outbox');
  @override
  int bw_bridge_take_outbox(int bridge, int out, int out_cap) => _bw_bridge_take_outbox(bridge, out, out_cap);

  late final _bw_bridge_apply_commands = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_apply_commands');
  @override
  int bw_bridge_apply_commands(int bridge, int entries, int len) => _bw_bridge_apply_commands(bridge, entries, len);

  late final _bw_bridge_set_controller = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_set_controller');
  @override
  int bw_bridge_set_controller(int bridge, int player_slot, int human) => _bw_bridge_set_controller(bridge, player_slot, human);

  late final _bw_bridge_state_hash = _lib.lookupFunction<ffi.Uint32 Function(ffi.IntPtr), int Function(int)>('bw_bridge_state_hash');
  @override
  int bw_bridge_state_hash(int bridge) => _bw_bridge_state_hash(bridge);

  late final _bw_bridge_replay_commands = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_replay_commands');
  @override
  int bw_bridge_replay_commands(int bridge, int log, int len, int end_frame) => _bw_bridge_replay_commands(bridge, log, len, end_frame);

  late final _bw_bridge_current_frame = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr), int Function(int)>('bw_bridge_current_frame');
  @override
  int bw_bridge_current_frame(int bridge) => _bw_bridge_current_frame(bridge);

  late final _bw_bridge_unit_count = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_unit_count');
  @override
  int bw_bridge_unit_count(int bridge, int player_slot) => _bw_bridge_unit_count(bridge, player_slot);

  late final _bw_bridge_minerals = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_minerals');
  @override
  int bw_bridge_minerals(int bridge, int player_slot) => _bw_bridge_minerals(bridge, player_slot);

  late final _bw_bridge_gas = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_gas');
  @override
  int bw_bridge_gas(int bridge, int player_slot) => _bw_bridge_gas(bridge, player_slot);

  late final _bw_bridge_supply = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_supply');
  @override
  int bw_bridge_supply(int bridge, int player_slot, int race, int out_used_raw, int out_available_raw) => _bw_bridge_supply(bridge, player_slot, race, out_used_raw, out_available_raw);

  late final _bw_bridge_get_draw_list = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int, int, int, int, int)>('bw_bridge_get_draw_list');
  @override
  int bw_bridge_get_draw_list(int bridge, int selected_owner, int view_x, int view_y, int view_w, int view_h, int out_items, int max_count) => _bw_bridge_get_draw_list(bridge, selected_owner, view_x, view_y, view_w, view_h, out_items, max_count);

  late final _bw_bridge_get_tileset_index = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr), int Function(int)>('bw_bridge_get_tileset_index');
  @override
  int bw_bridge_get_tileset_index(int bridge) => _bw_bridge_get_tileset_index(bridge);

  late final _bw_bridge_show_psi_fields = _lib.lookupFunction<ffi.Void Function(ffi.IntPtr, ffi.Int32), void Function(int, int)>('bw_bridge_show_psi_fields');
  @override
  void bw_bridge_show_psi_fields(int bridge, int owner) => _bw_bridge_show_psi_fields(bridge, owner);

  late final _bw_bridge_get_palette = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_get_palette');
  @override
  int bw_bridge_get_palette(int bridge, int out_rgba, int out_cap) => _bw_bridge_get_palette(bridge, out_rgba, out_cap);

  late final _bw_bridge_get_player_colors = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_get_player_colors');
  @override
  int bw_bridge_get_player_colors(int bridge, int out_colors, int out_cap) => _bw_bridge_get_player_colors(bridge, out_colors, out_cap);

  late final _bw_bridge_get_light_table = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_get_light_table');
  @override
  int bw_bridge_get_light_table(int bridge, int light_index, int out_table, int out_cap, int out_rows) => _bw_bridge_get_light_table(bridge, light_index, out_table, out_cap, out_rows);

  late final _bw_bridge_get_image_frame_size = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_get_image_frame_size');
  @override
  int bw_bridge_get_image_frame_size(int bridge, int image_type_id, int frame_index, int out_width, int out_height) => _bw_bridge_get_image_frame_size(bridge, image_type_id, frame_index, out_width, out_height);

  late final _bw_bridge_get_image_frame_count = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_get_image_frame_count');
  @override
  int bw_bridge_get_image_frame_count(int bridge, int image_type_id, int out_count) => _bw_bridge_get_image_frame_count(bridge, image_type_id, out_count);

  late final _bw_bridge_decode_image_frame = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int, int, int)>('bw_bridge_decode_image_frame');
  @override
  int bw_bridge_decode_image_frame(int bridge, int image_type_id, int frame_index, int flipped, int out_pixels, int out_cap) => _bw_bridge_decode_image_frame(bridge, image_type_id, frame_index, flipped, out_pixels, out_cap);

  late final _bw_bridge_get_map_tile_size = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_get_map_tile_size');
  @override
  int bw_bridge_get_map_tile_size(int bridge, int out_width, int out_height) => _bw_bridge_get_map_tile_size(bridge, out_width, out_height);

  late final _bw_bridge_get_tile_grid = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_get_tile_grid');
  @override
  int bw_bridge_get_tile_grid(int bridge, int out_megatiles, int out_cap) => _bw_bridge_get_tile_grid(bridge, out_megatiles, out_cap);

  late final _bw_bridge_decode_megatile = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_decode_megatile');
  @override
  int bw_bridge_decode_megatile(int bridge, int megatile_index, int out_pixels, int out_cap) => _bw_bridge_decode_megatile(bridge, megatile_index, out_pixels, out_cap);

  late final _bw_bridge_get_creep = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_get_creep');
  @override
  int bw_bridge_get_creep(int bridge, int out_tiles, int out_cap) => _bw_bridge_get_creep(bridge, out_tiles, out_cap);

  late final _bw_bridge_get_creep_edge = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int, int, int)>('bw_bridge_get_creep_edge');
  @override
  int bw_bridge_get_creep_edge(int bridge, int frame, int out_pixels, int out_cap, int out_width, int out_height, int out_count) => _bw_bridge_get_creep_edge(bridge, frame, out_pixels, out_cap, out_width, out_height, out_count);

  late final _bw_bridge_get_units = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_get_units');
  @override
  int bw_bridge_get_units(int bridge, int out_units, int max_count) => _bw_bridge_get_units(bridge, out_units, max_count);

  late final _bw_bridge_get_unit = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_get_unit');
  @override
  int bw_bridge_get_unit(int bridge, int unit_id, int out_unit) => _bw_bridge_get_unit(bridge, unit_id, out_unit);

  late final _bw_bridge_pick_unit_at = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_pick_unit_at');
  @override
  int bw_bridge_pick_unit_at(int bridge, int x, int y) => _bw_bridge_pick_unit_at(bridge, x, y);

  late final _bw_bridge_get_unit_type_info = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_get_unit_type_info');
  @override
  int bw_bridge_get_unit_type_info(int bridge, int unit_type_id, int out_info) => _bw_bridge_get_unit_type_info(bridge, unit_type_id, out_info);

  late final _bw_bridge_select_units = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_select_units');
  @override
  int bw_bridge_select_units(int bridge, int owner, int unit_ids, int count) => _bw_bridge_select_units(bridge, owner, unit_ids, count);

  late final _bw_bridge_get_selected_units = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_selected_units');
  @override
  int bw_bridge_get_selected_units(int bridge, int owner, int out_unit_ids, int max_count) => _bw_bridge_get_selected_units(bridge, owner, out_unit_ids, max_count);

  late final _bw_bridge_order = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int, int, int, int)>('bw_bridge_order');
  @override
  int bw_bridge_order(int bridge, int owner, int order, int x, int y, int target_unit_id, int queue) => _bw_bridge_order(bridge, owner, order, x, y, target_unit_id, queue);

  late final _bw_bridge_get_buildable = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_buildable');
  @override
  int bw_bridge_get_buildable(int bridge, int owner, int out_unit_type_ids, int max_count) => _bw_bridge_get_buildable(bridge, owner, out_unit_type_ids, max_count);

  late final _bw_bridge_train = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_train');
  @override
  int bw_bridge_train(int bridge, int owner, int unit_type_id) => _bw_bridge_train(bridge, owner, unit_type_id);

  late final _bw_bridge_can_place = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int, int)>('bw_bridge_can_place');
  @override
  int bw_bridge_can_place(int bridge, int owner, int unit_type_id, int tile_x, int tile_y) => _bw_bridge_can_place(bridge, owner, unit_type_id, tile_x, tile_y);

  late final _bw_bridge_build = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int, int)>('bw_bridge_build');
  @override
  int bw_bridge_build(int bridge, int owner, int unit_type_id, int tile_x, int tile_y) => _bw_bridge_build(bridge, owner, unit_type_id, tile_x, tile_y);

  late final _bw_bridge_cancel_last = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_cancel_last');
  @override
  int bw_bridge_cancel_last(int bridge, int owner) => _bw_bridge_cancel_last(bridge, owner);

  late final _bw_bridge_cancel_queue_slot = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_cancel_queue_slot');
  @override
  int bw_bridge_cancel_queue_slot(int bridge, int owner, int slot) => _bw_bridge_cancel_queue_slot(bridge, owner, slot);

  late final _bw_bridge_control_group = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_control_group');
  @override
  int bw_bridge_control_group(int bridge, int owner, int group, int action) => _bw_bridge_control_group(bridge, owner, group, action);

  late final _bw_bridge_get_tech_info = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int)>('bw_bridge_get_tech_info');
  @override
  int bw_bridge_get_tech_info(int bridge, int owner, int tech_id, int out_info) => _bw_bridge_get_tech_info(bridge, owner, tech_id, out_info);

  late final _bw_bridge_get_upgrade_info = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int)>('bw_bridge_get_upgrade_info');
  @override
  int bw_bridge_get_upgrade_info(int bridge, int owner, int upgrade_id, int out_info) => _bw_bridge_get_upgrade_info(bridge, owner, upgrade_id, out_info);

  late final _bw_bridge_get_researchable = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_researchable');
  @override
  int bw_bridge_get_researchable(int bridge, int owner, int out_tech_ids, int max_count) => _bw_bridge_get_researchable(bridge, owner, out_tech_ids, max_count);

  late final _bw_bridge_get_upgradable = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_upgradable');
  @override
  int bw_bridge_get_upgradable(int bridge, int owner, int out_upgrade_ids, int max_count) => _bw_bridge_get_upgradable(bridge, owner, out_upgrade_ids, max_count);

  late final _bw_bridge_research = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_research');
  @override
  int bw_bridge_research(int bridge, int owner, int tech_id) => _bw_bridge_research(bridge, owner, tech_id);

  late final _bw_bridge_upgrade = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_upgrade');
  @override
  int bw_bridge_upgrade(int bridge, int owner, int upgrade_id) => _bw_bridge_upgrade(bridge, owner, upgrade_id);

  late final _bw_bridge_can_use_tech = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_can_use_tech');
  @override
  int bw_bridge_can_use_tech(int bridge, int owner, int tech_id) => _bw_bridge_can_use_tech(bridge, owner, tech_id);

  late final _bw_bridge_cast = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int, int, int, int)>('bw_bridge_cast');
  @override
  int bw_bridge_cast(int bridge, int owner, int tech_id, int x, int y, int target_unit_id, int queue) => _bw_bridge_cast(bridge, owner, tech_id, x, y, target_unit_id, queue);

  late final _bw_bridge_action = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_action');
  @override
  int bw_bridge_action(int bridge, int owner, int action) => _bw_bridge_action(bridge, owner, action);

  late final _bw_bridge_get_loaded_units = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int)>('bw_bridge_get_loaded_units');
  @override
  int bw_bridge_get_loaded_units(int bridge, int unit_id, int out_unit_ids, int max_count) => _bw_bridge_get_loaded_units(bridge, unit_id, out_unit_ids, max_count);

  late final _bw_bridge_unload_unit = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32), int Function(int, int, int)>('bw_bridge_unload_unit');
  @override
  int bw_bridge_unload_unit(int bridge, int owner, int unit_id) => _bw_bridge_unload_unit(bridge, owner, unit_id);

  late final _bw_bridge_save_snapshot = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int)>('bw_bridge_save_snapshot');
  @override
  int bw_bridge_save_snapshot(int bridge, int out_data, int out_cap, int out_len) => _bw_bridge_save_snapshot(bridge, out_data, out_cap, out_len);

  late final _bw_bridge_load_snapshot = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_load_snapshot');
  @override
  int bw_bridge_load_snapshot(int bridge, int data, int len) => _bw_bridge_load_snapshot(bridge, data, len);

  late final _bw_bridge_set_ai_version = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_set_ai_version');
  @override
  int bw_bridge_set_ai_version(int bridge, int version) => _bw_bridge_set_ai_version(bridge, version);

  late final _bw_bridge_bot_compile = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int, int)>('bw_bridge_bot_compile');
  @override
  int bw_bridge_bot_compile(int bridge, int bundle, int profile, int out, int out_cap) => _bw_bridge_bot_compile(bridge, bundle, profile, out, out_cap);

  late final _bw_bridge_set_bot_profile = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int)>('bw_bridge_set_bot_profile');
  @override
  int bw_bridge_set_bot_profile(int bridge, int player_index, int bundle, int profile) => _bw_bridge_set_bot_profile(bridge, player_index, bundle, profile);

  late final _bw_bridge_set_rally = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.Int32, ffi.Int32), int Function(int, int, int, int, int)>('bw_bridge_set_rally');
  @override
  int bw_bridge_set_rally(int bridge, int owner, int x, int y, int target_unit_id) => _bw_bridge_set_rally(bridge, owner, x, y, target_unit_id);

  late final _bw_bridge_grp_load = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr), int Function(int, int)>('bw_bridge_grp_load');
  @override
  int bw_bridge_grp_load(int bridge, int path) => _bw_bridge_grp_load(bridge, path);

  late final _bw_bridge_grp_frame_count = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32), int Function(int, int)>('bw_bridge_grp_frame_count');
  @override
  int bw_bridge_grp_frame_count(int bridge, int handle) => _bw_bridge_grp_frame_count(bridge, handle);

  late final _bw_bridge_grp_frame_size = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_grp_frame_size');
  @override
  int bw_bridge_grp_frame_size(int bridge, int handle, int frame, int out_width, int out_height) => _bw_bridge_grp_frame_size(bridge, handle, frame, out_width, out_height);

  late final _bw_bridge_grp_decode = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.Int32, ffi.IntPtr, ffi.Int32), int Function(int, int, int, int, int)>('bw_bridge_grp_decode');
  @override
  int bw_bridge_grp_decode(int bridge, int handle, int frame, int out_pixels, int out_cap) => _bw_bridge_grp_decode(bridge, handle, frame, out_pixels, out_cap);

  late final _bw_bridge_load_pcx = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int, int)>('bw_bridge_load_pcx');
  @override
  int bw_bridge_load_pcx(int bridge, int path, int out_pixels, int out_cap, int out_width, int out_height) => _bw_bridge_load_pcx(bridge, path, out_pixels, out_cap, out_width, out_height);

  late final _bw_bridge_read_file = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_read_file');
  @override
  int bw_bridge_read_file(int bridge, int path, int out_data, int out_cap, int out_len) => _bw_bridge_read_file(bridge, path, out_data, out_cap, out_len);

  late final _bw_bridge_read_map_file = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int, int, int)>('bw_bridge_read_map_file');
  @override
  int bw_bridge_read_map_file(int bridge, int map_file, int path, int out_data, int out_cap, int out_len) => _bw_bridge_read_map_file(bridge, map_file, path, out_data, out_cap, out_len);

  late final _bw_bridge_load_pcx_rgba = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int, int)>('bw_bridge_load_pcx_rgba');
  @override
  int bw_bridge_load_pcx_rgba(int bridge, int path, int out_rgba, int out_cap, int out_width, int out_height) => _bw_bridge_load_pcx_rgba(bridge, path, out_rgba, out_cap, out_width, out_height);

  late final _bw_bridge_cursor_marker_image = _lib.lookupFunction<ffi.Int32 Function(), int Function()>('bw_bridge_cursor_marker_image');
  @override
  int bw_bridge_cursor_marker_image() => _bw_bridge_cursor_marker_image();

  late final _bw_bridge_get_selection_circle = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.IntPtr, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_get_selection_circle');
  @override
  int bw_bridge_get_selection_circle(int bridge, int unit_id, int out_image_type_id, int out_x, int out_y) => _bw_bridge_get_selection_circle(bridge, unit_id, out_image_type_id, out_x, out_y);

  late final _bw_bridge_sound_count = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr), int Function(int)>('bw_bridge_sound_count');
  @override
  int bw_bridge_sound_count(int bridge) => _bw_bridge_sound_count(bridge);

  late final _bw_bridge_get_sound_info = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int)>('bw_bridge_get_sound_info');
  @override
  int bw_bridge_get_sound_info(int bridge, int sound_id, int out_info) => _bw_bridge_get_sound_info(bridge, sound_id, out_info);

  late final _bw_bridge_load_sound = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.Int32, ffi.IntPtr, ffi.Int32, ffi.IntPtr), int Function(int, int, int, int, int)>('bw_bridge_load_sound');
  @override
  int bw_bridge_load_sound(int bridge, int sound_id, int out_data, int out_cap, int out_len) => _bw_bridge_load_sound(bridge, sound_id, out_data, out_cap, out_len);

  late final _bw_bridge_poll_sounds = _lib.lookupFunction<ffi.Int32 Function(ffi.IntPtr, ffi.IntPtr, ffi.Int32), int Function(int, int, int)>('bw_bridge_poll_sounds');
  @override
  int bw_bridge_poll_sounds(int bridge, int out_events, int max_count) => _bw_bridge_poll_sounds(bridge, out_events, max_count);

}
