// GENERATED by tool/gen_bridge_raw.py from engine/bridge/include/bw_bridge.h. Do not edit.
// ignore_for_file: non_constant_identifier_names, constant_identifier_names

// WebAssembly implementation of BridgeRaw: the bridge compiled by
// engine/web/build_wasm.sh (web/bwbridge.js + .wasm), created through the
// Emscripten module factory `createBwBridge` that web/index.html loads.

import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'dart:typed_data';

import 'bridge_raw.dart';

@JS('createBwBridge')
external JSPromise<JSObject> _createBwBridge();

class BridgeRawWeb extends BridgeRaw {
  final JSObject module;
  BridgeRawWeb._(this.module);

  static BridgeRawWeb? _instance;

  /// The engine module is created once per page and shared by every game,
  /// so the game data written into its file system stays there.
  static Future<BridgeRawWeb> open() async {
    return _instance ??= BridgeRawWeb._(await _createBwBridge().toDart);
  }

  int _call(String name, List<int> args) {
    final r = module.callMethodVarArgs<JSAny?>(name.toJS, [for (final a in args) a.toJS]);
    return r == null || r.isUndefinedOrNull ? 0 : (r as JSNumber).toDartInt;
  }

  JSUint8Array get _heap => module.getProperty<JSUint8Array>('HEAPU8'.toJS);

  @override
  int malloc(int size) {
    final p = _call('_malloc', [size <= 0 ? 1 : size]);
    bytes(p, size <= 0 ? 1 : size).fillRange(0, size <= 0 ? 1 : size, 0);
    return p;
  }

  @override
  void free(int address) => _call('_free', [address]);

  // The heap can grow (and be replaced), so always take a fresh view.
  @override
  Uint8List bytes(int address, int length) => _heap.toDart.buffer.asUint8List(address, length);

  @override
  Future<int> replayCommands(int bridge, Int32List log, int endFrame) async {
    final buf = malloc(log.isEmpty ? 4 : log.lengthInBytes);
    try {
      bytes(buf, log.lengthInBytes).setAll(0, log.buffer.asUint8List(log.offsetInBytes, log.lengthInBytes));
      return bw_bridge_replay_commands(bridge, buf, log.length, endFrame);
    } finally {
      free(buf);
    }
  }

  /// Emscripten's file system, where the game data lives (MEMFS).
  JSObject get fs => module.getProperty<JSObject>('FS'.toJS);

  @override
  int bw_bridge_abi_version() => _call('_bw_bridge_abi_version', []);

  @override
  int bw_bridge_create() => _call('_bw_bridge_create', []);

  @override
  void bw_bridge_destroy(int bridge) => _call('_bw_bridge_destroy', [bridge]);

  @override
  int bw_bridge_load_assets(int bridge, int data_dir) => _call('_bw_bridge_load_assets', [bridge, data_dir]);

  @override
  int bw_bridge_new_melee_game(int bridge, int map_file, int my_player_slot, int my_race) => _call('_bw_bridge_new_melee_game', [bridge, map_file, my_player_slot, my_race]);

  @override
  int bw_bridge_new_game(int bridge, int map_file, int setup, int out_slots) => _call('_bw_bridge_new_game', [bridge, map_file, setup, out_slots]);

  @override
  int bw_bridge_step(int bridge, int n_frames) => _call('_bw_bridge_step', [bridge, n_frames]);

  @override
  int bw_bridge_victory_state(int bridge, int player_slot) => _call('_bw_bridge_victory_state', [bridge, player_slot]);

  @override
  int bw_bridge_alliances(int bridge, int out, int max_count) => _call('_bw_bridge_alliances', [bridge, out, max_count]);

  @override
  int bw_bridge_alliance_set_open(int bridge, int player_slot, int open) => _call('_bw_bridge_alliance_set_open', [bridge, player_slot, open]);

  @override
  int bw_bridge_alliance_set_share(int bridge, int player_slot, int on) => _call('_bw_bridge_alliance_set_share', [bridge, player_slot, on]);

  @override
  int bw_bridge_alliance_get_share(int bridge, int player_slot) => _call('_bw_bridge_alliance_get_share', [bridge, player_slot]);

  @override
  int bw_bridge_alliance_set_defensive(int bridge, int player_slot, int on) => _call('_bw_bridge_alliance_set_defensive', [bridge, player_slot, on]);

  @override
  int bw_bridge_alliance_get_defensive(int bridge, int player_slot) => _call('_bw_bridge_alliance_get_defensive', [bridge, player_slot]);

  @override
  int bw_bridge_alliance_kick(int bridge, int by, int target) => _call('_bw_bridge_alliance_kick', [bridge, by, target]);

  @override
  int bw_bridge_alliance_set_capped(int bridge, int on) => _call('_bw_bridge_alliance_set_capped', [bridge, on]);

  @override
  int bw_bridge_alliance_invite(int bridge, int from, int to) => _call('_bw_bridge_alliance_invite', [bridge, from, to]);

  @override
  int bw_bridge_alliance_respond(int bridge, int player_slot, int from, int accept) => _call('_bw_bridge_alliance_respond', [bridge, player_slot, from, accept]);

  @override
  int bw_bridge_alliance_leave(int bridge, int player_slot) => _call('_bw_bridge_alliance_leave', [bridge, player_slot]);

  @override
  int bw_bridge_alliance_surrender(int bridge, int from, int to) => _call('_bw_bridge_alliance_surrender', [bridge, from, to]);

  @override
  int bw_bridge_alliance_answer_surrender(int bridge, int player_slot, int from, int accept) => _call('_bw_bridge_alliance_answer_surrender', [bridge, player_slot, from, accept]);

  @override
  int bw_bridge_player_stats(int bridge, int player_slot, int out) => _call('_bw_bridge_player_stats', [bridge, player_slot, out]);

  @override
  int bw_bridge_poll_alliance_events(int bridge, int out, int max_count) => _call('_bw_bridge_poll_alliance_events', [bridge, out, max_count]);

  @override
  int bw_bridge_set_autoplay(int bridge, int player_slot, int modes) => _call('_bw_bridge_set_autoplay', [bridge, player_slot, modes]);

  @override
  int bw_bridge_get_autoplay(int bridge, int player_slot) => _call('_bw_bridge_get_autoplay', [bridge, player_slot]);

  @override
  void bw_bridge_set_viewer(int bridge, int player_slot) => _call('_bw_bridge_set_viewer', [bridge, player_slot]);

  @override
  int bw_bridge_get_fog(int bridge, int player_slot, int out_tiles, int out_cap) => _call('_bw_bridge_get_fog', [bridge, player_slot, out_tiles, out_cap]);

  @override
  int bw_bridge_explore_map(int bridge, int player_slot) => _call('_bw_bridge_explore_map', [bridge, player_slot]);

  @override
  void bw_bridge_set_legacy_unit_ids(int bridge, int on) => _call('_bw_bridge_set_legacy_unit_ids', [bridge, on]);

  @override
  int bw_bridge_command_log(int bridge, int out, int out_cap) => _call('_bw_bridge_command_log', [bridge, out, out_cap]);

  @override
  void bw_bridge_set_deferred(int bridge, int on) => _call('_bw_bridge_set_deferred', [bridge, on]);

  @override
  int bw_bridge_take_outbox(int bridge, int out, int out_cap) => _call('_bw_bridge_take_outbox', [bridge, out, out_cap]);

  @override
  int bw_bridge_apply_commands(int bridge, int entries, int len) => _call('_bw_bridge_apply_commands', [bridge, entries, len]);

  @override
  int bw_bridge_set_controller(int bridge, int player_slot, int human) => _call('_bw_bridge_set_controller', [bridge, player_slot, human]);

  @override
  int bw_bridge_state_hash(int bridge) => _call('_bw_bridge_state_hash', [bridge]) & 0xffffffff;

  @override
  int bw_bridge_replay_commands(int bridge, int log, int len, int end_frame) => _call('_bw_bridge_replay_commands', [bridge, log, len, end_frame]);

  @override
  int bw_bridge_current_frame(int bridge) => _call('_bw_bridge_current_frame', [bridge]);

  @override
  int bw_bridge_unit_count(int bridge, int player_slot) => _call('_bw_bridge_unit_count', [bridge, player_slot]);

  @override
  int bw_bridge_minerals(int bridge, int player_slot) => _call('_bw_bridge_minerals', [bridge, player_slot]);

  @override
  int bw_bridge_gas(int bridge, int player_slot) => _call('_bw_bridge_gas', [bridge, player_slot]);

  @override
  int bw_bridge_supply(int bridge, int player_slot, int race, int out_used_raw, int out_available_raw) => _call('_bw_bridge_supply', [bridge, player_slot, race, out_used_raw, out_available_raw]);

  @override
  int bw_bridge_get_draw_list(int bridge, int selected_owner, int view_x, int view_y, int view_w, int view_h, int out_items, int max_count) => _call('_bw_bridge_get_draw_list', [bridge, selected_owner, view_x, view_y, view_w, view_h, out_items, max_count]);

  @override
  int bw_bridge_get_tileset_index(int bridge) => _call('_bw_bridge_get_tileset_index', [bridge]);

  @override
  void bw_bridge_show_psi_fields(int bridge, int owner) => _call('_bw_bridge_show_psi_fields', [bridge, owner]);

  @override
  int bw_bridge_get_palette(int bridge, int out_rgba, int out_cap) => _call('_bw_bridge_get_palette', [bridge, out_rgba, out_cap]);

  @override
  int bw_bridge_get_player_colors(int bridge, int out_colors, int out_cap) => _call('_bw_bridge_get_player_colors', [bridge, out_colors, out_cap]);

  @override
  int bw_bridge_get_light_table(int bridge, int light_index, int out_table, int out_cap, int out_rows) => _call('_bw_bridge_get_light_table', [bridge, light_index, out_table, out_cap, out_rows]);

  @override
  int bw_bridge_get_image_frame_size(int bridge, int image_type_id, int frame_index, int out_width, int out_height) => _call('_bw_bridge_get_image_frame_size', [bridge, image_type_id, frame_index, out_width, out_height]);

  @override
  int bw_bridge_get_image_frame_count(int bridge, int image_type_id, int out_count) => _call('_bw_bridge_get_image_frame_count', [bridge, image_type_id, out_count]);

  @override
  int bw_bridge_decode_image_frame(int bridge, int image_type_id, int frame_index, int flipped, int out_pixels, int out_cap) => _call('_bw_bridge_decode_image_frame', [bridge, image_type_id, frame_index, flipped, out_pixels, out_cap]);

  @override
  int bw_bridge_get_map_tile_size(int bridge, int out_width, int out_height) => _call('_bw_bridge_get_map_tile_size', [bridge, out_width, out_height]);

  @override
  int bw_bridge_get_tile_grid(int bridge, int out_megatiles, int out_cap) => _call('_bw_bridge_get_tile_grid', [bridge, out_megatiles, out_cap]);

  @override
  int bw_bridge_decode_megatile(int bridge, int megatile_index, int out_pixels, int out_cap) => _call('_bw_bridge_decode_megatile', [bridge, megatile_index, out_pixels, out_cap]);

  @override
  int bw_bridge_get_creep(int bridge, int out_tiles, int out_cap) => _call('_bw_bridge_get_creep', [bridge, out_tiles, out_cap]);

  @override
  int bw_bridge_get_creep_edge(int bridge, int frame, int out_pixels, int out_cap, int out_width, int out_height, int out_count) => _call('_bw_bridge_get_creep_edge', [bridge, frame, out_pixels, out_cap, out_width, out_height, out_count]);

  @override
  int bw_bridge_get_units(int bridge, int out_units, int max_count) => _call('_bw_bridge_get_units', [bridge, out_units, max_count]);

  @override
  int bw_bridge_get_unit(int bridge, int unit_id, int out_unit) => _call('_bw_bridge_get_unit', [bridge, unit_id, out_unit]);

  @override
  int bw_bridge_pick_unit_at(int bridge, int x, int y) => _call('_bw_bridge_pick_unit_at', [bridge, x, y]);

  @override
  int bw_bridge_get_unit_type_info(int bridge, int unit_type_id, int out_info) => _call('_bw_bridge_get_unit_type_info', [bridge, unit_type_id, out_info]);

  @override
  int bw_bridge_select_units(int bridge, int owner, int unit_ids, int count) => _call('_bw_bridge_select_units', [bridge, owner, unit_ids, count]);

  @override
  int bw_bridge_get_selected_units(int bridge, int owner, int out_unit_ids, int max_count) => _call('_bw_bridge_get_selected_units', [bridge, owner, out_unit_ids, max_count]);

  @override
  int bw_bridge_order(int bridge, int owner, int order, int x, int y, int target_unit_id, int queue) => _call('_bw_bridge_order', [bridge, owner, order, x, y, target_unit_id, queue]);

  @override
  int bw_bridge_get_buildable(int bridge, int owner, int out_unit_type_ids, int max_count) => _call('_bw_bridge_get_buildable', [bridge, owner, out_unit_type_ids, max_count]);

  @override
  int bw_bridge_train(int bridge, int owner, int unit_type_id) => _call('_bw_bridge_train', [bridge, owner, unit_type_id]);

  @override
  int bw_bridge_can_place(int bridge, int owner, int unit_type_id, int tile_x, int tile_y) => _call('_bw_bridge_can_place', [bridge, owner, unit_type_id, tile_x, tile_y]);

  @override
  int bw_bridge_build(int bridge, int owner, int unit_type_id, int tile_x, int tile_y) => _call('_bw_bridge_build', [bridge, owner, unit_type_id, tile_x, tile_y]);

  @override
  int bw_bridge_cancel_last(int bridge, int owner) => _call('_bw_bridge_cancel_last', [bridge, owner]);

  @override
  int bw_bridge_cancel_queue_slot(int bridge, int owner, int slot) => _call('_bw_bridge_cancel_queue_slot', [bridge, owner, slot]);

  @override
  int bw_bridge_control_group(int bridge, int owner, int group, int action) => _call('_bw_bridge_control_group', [bridge, owner, group, action]);

  @override
  int bw_bridge_get_tech_info(int bridge, int owner, int tech_id, int out_info) => _call('_bw_bridge_get_tech_info', [bridge, owner, tech_id, out_info]);

  @override
  int bw_bridge_get_upgrade_info(int bridge, int owner, int upgrade_id, int out_info) => _call('_bw_bridge_get_upgrade_info', [bridge, owner, upgrade_id, out_info]);

  @override
  int bw_bridge_get_researchable(int bridge, int owner, int out_tech_ids, int max_count) => _call('_bw_bridge_get_researchable', [bridge, owner, out_tech_ids, max_count]);

  @override
  int bw_bridge_get_upgradable(int bridge, int owner, int out_upgrade_ids, int max_count) => _call('_bw_bridge_get_upgradable', [bridge, owner, out_upgrade_ids, max_count]);

  @override
  int bw_bridge_research(int bridge, int owner, int tech_id) => _call('_bw_bridge_research', [bridge, owner, tech_id]);

  @override
  int bw_bridge_upgrade(int bridge, int owner, int upgrade_id) => _call('_bw_bridge_upgrade', [bridge, owner, upgrade_id]);

  @override
  int bw_bridge_can_use_tech(int bridge, int owner, int tech_id) => _call('_bw_bridge_can_use_tech', [bridge, owner, tech_id]);

  @override
  int bw_bridge_cast(int bridge, int owner, int tech_id, int x, int y, int target_unit_id, int queue) => _call('_bw_bridge_cast', [bridge, owner, tech_id, x, y, target_unit_id, queue]);

  @override
  int bw_bridge_action(int bridge, int owner, int action) => _call('_bw_bridge_action', [bridge, owner, action]);

  @override
  int bw_bridge_get_loaded_units(int bridge, int unit_id, int out_unit_ids, int max_count) => _call('_bw_bridge_get_loaded_units', [bridge, unit_id, out_unit_ids, max_count]);

  @override
  int bw_bridge_unload_unit(int bridge, int owner, int unit_id) => _call('_bw_bridge_unload_unit', [bridge, owner, unit_id]);

  @override
  int bw_bridge_save_snapshot(int bridge, int out_data, int out_cap, int out_len) => _call('_bw_bridge_save_snapshot', [bridge, out_data, out_cap, out_len]);

  @override
  int bw_bridge_load_snapshot(int bridge, int data, int len) => _call('_bw_bridge_load_snapshot', [bridge, data, len]);

  @override
  int bw_bridge_set_ai_version(int bridge, int version) => _call('_bw_bridge_set_ai_version', [bridge, version]);

  @override
  int bw_bridge_bot_compile(int bridge, int bundle, int profile, int out, int out_cap) => _call('_bw_bridge_bot_compile', [bridge, bundle, profile, out, out_cap]);

  @override
  int bw_bridge_set_bot_profile(int bridge, int player_index, int bundle, int profile) => _call('_bw_bridge_set_bot_profile', [bridge, player_index, bundle, profile]);

  @override
  int bw_bridge_set_rally(int bridge, int owner, int x, int y, int target_unit_id) => _call('_bw_bridge_set_rally', [bridge, owner, x, y, target_unit_id]);

  @override
  int bw_bridge_grp_load(int bridge, int path) => _call('_bw_bridge_grp_load', [bridge, path]);

  @override
  int bw_bridge_grp_frame_count(int bridge, int handle) => _call('_bw_bridge_grp_frame_count', [bridge, handle]);

  @override
  int bw_bridge_grp_frame_size(int bridge, int handle, int frame, int out_width, int out_height) => _call('_bw_bridge_grp_frame_size', [bridge, handle, frame, out_width, out_height]);

  @override
  int bw_bridge_grp_decode(int bridge, int handle, int frame, int out_pixels, int out_cap) => _call('_bw_bridge_grp_decode', [bridge, handle, frame, out_pixels, out_cap]);

  @override
  int bw_bridge_load_pcx(int bridge, int path, int out_pixels, int out_cap, int out_width, int out_height) => _call('_bw_bridge_load_pcx', [bridge, path, out_pixels, out_cap, out_width, out_height]);

  @override
  int bw_bridge_read_file(int bridge, int path, int out_data, int out_cap, int out_len) => _call('_bw_bridge_read_file', [bridge, path, out_data, out_cap, out_len]);

  @override
  int bw_bridge_read_map_file(int bridge, int map_file, int path, int out_data, int out_cap, int out_len) => _call('_bw_bridge_read_map_file', [bridge, map_file, path, out_data, out_cap, out_len]);

  @override
  int bw_bridge_load_pcx_rgba(int bridge, int path, int out_rgba, int out_cap, int out_width, int out_height) => _call('_bw_bridge_load_pcx_rgba', [bridge, path, out_rgba, out_cap, out_width, out_height]);

  @override
  int bw_bridge_cursor_marker_image() => _call('_bw_bridge_cursor_marker_image', []);

  @override
  int bw_bridge_get_selection_circle(int bridge, int unit_id, int out_image_type_id, int out_x, int out_y) => _call('_bw_bridge_get_selection_circle', [bridge, unit_id, out_image_type_id, out_x, out_y]);

  @override
  int bw_bridge_sound_count(int bridge) => _call('_bw_bridge_sound_count', [bridge]);

  @override
  int bw_bridge_get_sound_info(int bridge, int sound_id, int out_info) => _call('_bw_bridge_get_sound_info', [bridge, sound_id, out_info]);

  @override
  int bw_bridge_load_sound(int bridge, int sound_id, int out_data, int out_cap, int out_len) => _call('_bw_bridge_load_sound', [bridge, sound_id, out_data, out_cap, out_len]);

  @override
  int bw_bridge_poll_sounds(int bridge, int out_events, int max_count) => _call('_bw_bridge_poll_sounds', [bridge, out_events, max_count]);

}
