// GENERATED FILE — do not edit by hand.
// Source: engine/bridge/include/bw_bridge.h
// Regenerate with: dart run ffigen --config ffigen.yaml
// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated FFI bindings for the Brood War bridge (engine/bridge/include/bw_bridge.h).
class BwBridgeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BwBridgeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BwBridgeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int bw_bridge_abi_version() {
    return _bw_bridge_abi_version();
  }

  late final _bw_bridge_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('bw_bridge_abi_version');
  late final _bw_bridge_abi_version = _bw_bridge_abi_versionPtr
      .asFunction<int Function()>();

  /// --- Lifecycle -------------------------------------------------------------
  ffi.Pointer<bw_bridge_t> bw_bridge_create() {
    return _bw_bridge_create();
  }

  late final _bw_bridge_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<bw_bridge_t> Function()>>(
        'bw_bridge_create',
      );
  late final _bw_bridge_create = _bw_bridge_createPtr
      .asFunction<ffi.Pointer<bw_bridge_t> Function()>();

  void bw_bridge_destroy(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_destroy(bridge);
  }

  late final _bw_bridge_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_destroy',
      );
  late final _bw_bridge_destroy = _bw_bridge_destroyPtr
      .asFunction<void Function(ffi.Pointer<bw_bridge_t>)>();

  /// Loads StarDat.mpq/BrooDat.mpq/Patch_rt.mpq from data_dir. data_dir must be
  /// a user-supplied location (their own copy), never a path inside the app
  /// bundle. See docs/third_party_licensing.md.
  bw_status bw_bridge_load_assets(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> data_dir,
  ) {
    return bw_status.fromValue(_bw_bridge_load_assets(bridge, data_dir));
  }

  late final _bw_bridge_load_assetsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
        >
      >('bw_bridge_load_assets');
  late final _bw_bridge_load_assets = _bw_bridge_load_assetsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
      >();

  /// Starts a melee game on map_file with the local player in my_player_slot
  /// (0-11) as my_race (0=zerg, 1=terran, 2=protoss). Other slots are inactive.
  bw_status bw_bridge_new_melee_game(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> map_file,
    int my_player_slot,
    int my_race,
  ) {
    return bw_status.fromValue(
      _bw_bridge_new_melee_game(bridge, map_file, my_player_slot, my_race),
    );
  }

  late final _bw_bridge_new_melee_gamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('bw_bridge_new_melee_game');
  late final _bw_bridge_new_melee_game = _bw_bridge_new_melee_gamePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>, int, int)
      >();

  /// Advances the simulation by n_frames (synchronous).
  bw_status bw_bridge_step(ffi.Pointer<bw_bridge_t> bridge, int n_frames) {
    return bw_status.fromValue(_bw_bridge_step(bridge, n_frames));
  }

  late final _bw_bridge_stepPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_step');
  late final _bw_bridge_step = _bw_bridge_stepPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  /// --- Scalar queries --------------------------------------------------------
  int bw_bridge_current_frame(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_current_frame(bridge);
  }

  late final _bw_bridge_current_framePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_current_frame',
      );
  late final _bw_bridge_current_frame = _bw_bridge_current_framePtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>)>();

  int bw_bridge_unit_count(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_unit_count(bridge, player_slot);
  }

  late final _bw_bridge_unit_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_unit_count');
  late final _bw_bridge_unit_count = _bw_bridge_unit_countPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  int bw_bridge_minerals(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_minerals(bridge, player_slot);
  }

  late final _bw_bridge_mineralsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_minerals');
  late final _bw_bridge_minerals = _bw_bridge_mineralsPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  int bw_bridge_gas(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_gas(bridge, player_slot);
  }

  late final _bw_bridge_gasPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_gas');
  late final _bw_bridge_gas = _bw_bridge_gasPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  /// Supply in BW's half-unit fixed point (divide by 2 for display).
  bw_status bw_bridge_supply(
    ffi.Pointer<bw_bridge_t> bridge,
    int player_slot,
    int race,
    ffi.Pointer<ffi.Int> out_used_raw,
    ffi.Pointer<ffi.Int> out_available_raw,
  ) {
    return bw_status.fromValue(
      _bw_bridge_supply(
        bridge,
        player_slot,
        race,
        out_used_raw,
        out_available_raw,
      ),
    );
  }

  late final _bw_bridge_supplyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_supply');
  late final _bw_bridge_supply = _bw_bridge_supplyPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  /// Fills out_items with everything visible inside the map-pixel rectangle
  /// (view_x, view_y, view_w, view_h), in draw order, with selection circles
  /// for selected_owner's current selection inserted where OpenBW draws them.
  /// Returns the number written, or -1 on error.
  int bw_bridge_get_draw_list(
    ffi.Pointer<bw_bridge_t> bridge,
    int selected_owner,
    int view_x,
    int view_y,
    int view_w,
    int view_h,
    ffi.Pointer<bw_draw_item> out_items,
    int max_count,
  ) {
    return _bw_bridge_get_draw_list(
      bridge,
      selected_owner,
      view_x,
      view_y,
      view_w,
      view_h,
      out_items,
      max_count,
    );
  }

  late final _bw_bridge_get_draw_listPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<bw_draw_item>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_draw_list');
  late final _bw_bridge_get_draw_list = _bw_bridge_get_draw_listPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          int,
          int,
          int,
          ffi.Pointer<bw_draw_item>,
          int,
        )
      >();

  int bw_bridge_get_tileset_index(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_get_tileset_index(bridge);
  }

  late final _bw_bridge_get_tileset_indexPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_get_tileset_index',
      );
  late final _bw_bridge_get_tileset_index = _bw_bridge_get_tileset_indexPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>)>();

  /// 256 RGBA8888 entries (1024 bytes).
  bw_status bw_bridge_get_palette(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Uint8> out_rgba,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_palette(bridge, out_rgba, out_cap),
    );
  }

  late final _bw_bridge_get_palettePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_palette');
  late final _bw_bridge_get_palette = _bw_bridge_get_palettePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// 16 colors x 8 shades (128 bytes): palette indices 8..15 in a decoded frame
  /// are remapped through row color_index before the palette lookup.
  bw_status bw_bridge_get_player_colors(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Uint8> out_colors,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_player_colors(bridge, out_colors, out_cap),
    );
  }

  late final _bw_bridge_get_player_colorsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_player_colors');
  late final _bw_bridge_get_player_colors = _bw_bridge_get_player_colorsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Light (glow) table light_index (1-based, as in bw_draw_item.color_shift):
  /// rows x 256 palette indices. A glow pixel with value v drawn over palette
  /// color d becomes palette color table[(v - 1) * 256 + d]. out_cap must be
  /// >= rows * 256; pass out_table NULL to just query *out_rows.
  bw_status bw_bridge_get_light_table(
    ffi.Pointer<bw_bridge_t> bridge,
    int light_index,
    ffi.Pointer<ffi.Uint8> out_table,
    int out_cap,
    ffi.Pointer<ffi.Int> out_rows,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_light_table(
        bridge,
        light_index,
        out_table,
        out_cap,
        out_rows,
      ),
    );
  }

  late final _bw_bridge_get_light_tablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_light_table');
  late final _bw_bridge_get_light_table = _bw_bridge_get_light_tablePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int>,
        )
      >();

  bw_status bw_bridge_get_image_frame_size(
    ffi.Pointer<bw_bridge_t> bridge,
    int image_type_id,
    int frame_index,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_image_frame_size(
        bridge,
        image_type_id,
        frame_index,
        out_width,
        out_height,
      ),
    );
  }

  late final _bw_bridge_get_image_frame_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_image_frame_size');
  late final _bw_bridge_get_image_frame_size =
      _bw_bridge_get_image_frame_sizePtr
          .asFunction<
            int Function(
              ffi.Pointer<bw_bridge_t>,
              int,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
            )
          >();

  bw_status bw_bridge_get_image_frame_count(
    ffi.Pointer<bw_bridge_t> bridge,
    int image_type_id,
    ffi.Pointer<ffi.Int> out_count,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_image_frame_count(bridge, image_type_id, out_count),
    );
  }

  late final _bw_bridge_get_image_frame_countPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_image_frame_count');
  late final _bw_bridge_get_image_frame_count =
      _bw_bridge_get_image_frame_countPtr
          .asFunction<
            int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int>)
          >();

  /// width*height palette-index bytes, 0 = transparent. No player recoloring.
  bw_status bw_bridge_decode_image_frame(
    ffi.Pointer<bw_bridge_t> bridge,
    int image_type_id,
    int frame_index,
    int flipped,
    ffi.Pointer<ffi.Uint8> out_pixels,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_decode_image_frame(
        bridge,
        image_type_id,
        frame_index,
        flipped,
        out_pixels,
        out_cap,
      ),
    );
  }

  late final _bw_bridge_decode_image_framePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_decode_image_frame');
  late final _bw_bridge_decode_image_frame = _bw_bridge_decode_image_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// --- Terrain ---------------------------------------------------------------
  bw_status bw_bridge_get_map_tile_size(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_map_tile_size(bridge, out_width, out_height),
    );
  }

  late final _bw_bridge_get_map_tile_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_map_tile_size');
  late final _bw_bridge_get_map_tile_size = _bw_bridge_get_map_tile_sizePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  bw_status bw_bridge_get_tile_grid(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Uint16> out_megatiles,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_tile_grid(bridge, out_megatiles, out_cap),
    );
  }

  late final _bw_bridge_get_tile_gridPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Uint16>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_tile_grid');
  late final _bw_bridge_get_tile_grid = _bw_bridge_get_tile_gridPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Uint16>, int)
      >();

  bw_status bw_bridge_decode_megatile(
    ffi.Pointer<bw_bridge_t> bridge,
    int megatile_index,
    ffi.Pointer<ffi.Uint8> out_pixels,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_decode_megatile(bridge, megatile_index, out_pixels, out_cap),
    );
  }

  late final _bw_bridge_decode_megatilePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_decode_megatile');
  late final _bw_bridge_decode_megatile = _bw_bridge_decode_megatilePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// All live units of every player. Returns count written, -1 on error.
  int bw_bridge_get_units(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<bw_unit_info> out_units,
    int max_count,
  ) {
    return _bw_bridge_get_units(bridge, out_units, max_count);
  }

  late final _bw_bridge_get_unitsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<bw_unit_info>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_units');
  late final _bw_bridge_get_units = _bw_bridge_get_unitsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<bw_unit_info>, int)
      >();

  bw_status bw_bridge_get_unit(
    ffi.Pointer<bw_bridge_t> bridge,
    int unit_id,
    ffi.Pointer<bw_unit_info> out_unit,
  ) {
    return bw_status.fromValue(_bw_bridge_get_unit(bridge, unit_id, out_unit));
  }

  late final _bw_bridge_get_unitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int32,
            ffi.Pointer<bw_unit_info>,
          )
        >
      >('bw_bridge_get_unit');
  late final _bw_bridge_get_unit = _bw_bridge_get_unitPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<bw_unit_info>)
      >();

  /// Finds the unit whose sprite covers map position (x, y), 0 if none.
  int bw_bridge_pick_unit_at(ffi.Pointer<bw_bridge_t> bridge, int x, int y) {
    return _bw_bridge_pick_unit_at(bridge, x, y);
  }

  late final _bw_bridge_pick_unit_atPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_pick_unit_at');
  late final _bw_bridge_pick_unit_at = _bw_bridge_pick_unit_atPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  bw_status bw_bridge_get_unit_type_info(
    ffi.Pointer<bw_bridge_t> bridge,
    int unit_type_id,
    ffi.Pointer<bw_unit_type_info> out_info,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_unit_type_info(bridge, unit_type_id, out_info),
    );
  }

  late final _bw_bridge_get_unit_type_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<bw_unit_type_info>,
          )
        >
      >('bw_bridge_get_unit_type_info');
  late final _bw_bridge_get_unit_type_info = _bw_bridge_get_unit_type_infoPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          ffi.Pointer<bw_unit_type_info>,
        )
      >();

  /// Replaces the selection (max 12, as in the original game).
  bw_status bw_bridge_select_units(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    ffi.Pointer<ffi.Int32> unit_ids,
    int count,
  ) {
    return bw_status.fromValue(
      _bw_bridge_select_units(bridge, owner, unit_ids, count),
    );
  }

  late final _bw_bridge_select_unitsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int32>,
            ffi.Int,
          )
        >
      >('bw_bridge_select_units');
  late final _bw_bridge_select_units = _bw_bridge_select_unitsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int32>, int)
      >();

  int bw_bridge_get_selected_units(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    ffi.Pointer<ffi.Int32> out_unit_ids,
    int max_count,
  ) {
    return _bw_bridge_get_selected_units(
      bridge,
      owner,
      out_unit_ids,
      max_count,
    );
  }

  late final _bw_bridge_get_selected_unitsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int32>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_selected_units');
  late final _bw_bridge_get_selected_units = _bw_bridge_get_selected_unitsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int32>, int)
      >();

  /// Issues an order to the current selection.
  bw_status bw_bridge_order(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int order,
    int x,
    int y,
    int target_unit_id,
    int queue,
  ) {
    return bw_status.fromValue(
      _bw_bridge_order(bridge, owner, order, x, y, target_unit_id, queue),
    );
  }

  late final _bw_bridge_orderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int32,
            ffi.Int,
          )
        >
      >('bw_bridge_order');
  late final _bw_bridge_order = _bw_bridge_orderPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, int, int, int, int, int)
      >();

  /// Unit types the single selected unit can build or train right now
  /// (OpenBW's unit_can_build: tech requirements met; cost is not checked).
  int bw_bridge_get_buildable(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    ffi.Pointer<ffi.Int32> out_unit_type_ids,
    int max_count,
  ) {
    return _bw_bridge_get_buildable(
      bridge,
      owner,
      out_unit_type_ids,
      max_count,
    );
  }

  late final _bw_bridge_get_buildablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int32>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_buildable');
  late final _bw_bridge_get_buildable = _bw_bridge_get_buildablePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int32>, int)
      >();

  /// Trains (units) or builds (addons) unit_type_id from the selected unit.
  bw_status bw_bridge_train(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int unit_type_id,
  ) {
    return bw_status.fromValue(_bw_bridge_train(bridge, owner, unit_type_id));
  }

  late final _bw_bridge_trainPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_train');
  late final _bw_bridge_train = _bw_bridge_trainPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  /// Whether the selected builder could place building unit_type_id with its
  /// top-left corner on tile (tile_x, tile_y).
  int bw_bridge_can_place(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int unit_type_id,
    int tile_x,
    int tile_y,
  ) {
    return _bw_bridge_can_place(bridge, owner, unit_type_id, tile_x, tile_y);
  }

  late final _bw_bridge_can_placePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('bw_bridge_can_place');
  late final _bw_bridge_can_place = _bw_bridge_can_placePtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int, int, int)>();

  /// Orders the selected builder to construct unit_type_id at tile (tile_x, tile_y).
  bw_status bw_bridge_build(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int unit_type_id,
    int tile_x,
    int tile_y,
  ) {
    return bw_status.fromValue(
      _bw_bridge_build(bridge, owner, unit_type_id, tile_x, tile_y),
    );
  }

  late final _bw_bridge_buildPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
          )
        >
      >('bw_bridge_build');
  late final _bw_bridge_build = _bw_bridge_buildPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int, int, int)>();

  /// Cancels the last item of the selected building's queue (refunds it).
  bw_status bw_bridge_cancel_last(ffi.Pointer<bw_bridge_t> bridge, int owner) {
    return bw_status.fromValue(_bw_bridge_cancel_last(bridge, owner));
  }

  late final _bw_bridge_cancel_lastPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_cancel_last');
  late final _bw_bridge_cancel_last = _bw_bridge_cancel_lastPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  /// Cancels queue slot `slot` (0 = the one in production) of the selected
  /// building, as clicking a queued unit does in the original.
  bw_status bw_bridge_cancel_queue_slot(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int slot,
  ) {
    return bw_status.fromValue(
      _bw_bridge_cancel_queue_slot(bridge, owner, slot),
    );
  }

  late final _bw_bridge_cancel_queue_slotPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_cancel_queue_slot');
  late final _bw_bridge_cancel_queue_slot = _bw_bridge_cancel_queue_slotPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  bw_status bw_bridge_control_group(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int group,
    int action,
  ) {
    return bw_status.fromValue(
      _bw_bridge_control_group(bridge, owner, group, action),
    );
  }

  late final _bw_bridge_control_groupPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int, ffi.Int)
        >
      >('bw_bridge_control_group');
  late final _bw_bridge_control_group = _bw_bridge_control_groupPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int, int)>();

  bw_status bw_bridge_get_tech_info(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int tech_id,
    ffi.Pointer<bw_tech_info> out_info,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_tech_info(bridge, owner, tech_id, out_info),
    );
  }

  late final _bw_bridge_get_tech_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<bw_tech_info>,
          )
        >
      >('bw_bridge_get_tech_info');
  late final _bw_bridge_get_tech_info = _bw_bridge_get_tech_infoPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          ffi.Pointer<bw_tech_info>,
        )
      >();

  bw_status bw_bridge_get_upgrade_info(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int upgrade_id,
    ffi.Pointer<bw_upgrade_info> out_info,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_upgrade_info(bridge, owner, upgrade_id, out_info),
    );
  }

  late final _bw_bridge_get_upgrade_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<bw_upgrade_info>,
          )
        >
      >('bw_bridge_get_upgrade_info');
  late final _bw_bridge_get_upgrade_info = _bw_bridge_get_upgrade_infoPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          ffi.Pointer<bw_upgrade_info>,
        )
      >();

  /// What the single selected building can research / upgrade right now
  /// (OpenBW's unit_can_research / unit_can_upgrade).
  int bw_bridge_get_researchable(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    ffi.Pointer<ffi.Int32> out_tech_ids,
    int max_count,
  ) {
    return _bw_bridge_get_researchable(bridge, owner, out_tech_ids, max_count);
  }

  late final _bw_bridge_get_researchablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int32>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_researchable');
  late final _bw_bridge_get_researchable = _bw_bridge_get_researchablePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int32>, int)
      >();

  int bw_bridge_get_upgradable(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    ffi.Pointer<ffi.Int32> out_upgrade_ids,
    int max_count,
  ) {
    return _bw_bridge_get_upgradable(bridge, owner, out_upgrade_ids, max_count);
  }

  late final _bw_bridge_get_upgradablePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Int32>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_upgradable');
  late final _bw_bridge_get_upgradable = _bw_bridge_get_upgradablePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<ffi.Int32>, int)
      >();

  bw_status bw_bridge_research(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int tech_id,
  ) {
    return bw_status.fromValue(_bw_bridge_research(bridge, owner, tech_id));
  }

  late final _bw_bridge_researchPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_research');
  late final _bw_bridge_research = _bw_bridge_researchPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  bw_status bw_bridge_upgrade(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int upgrade_id,
  ) {
    return bw_status.fromValue(_bw_bridge_upgrade(bridge, owner, upgrade_id));
  }

  late final _bw_bridge_upgradePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_upgrade');
  late final _bw_bridge_upgrade = _bw_bridge_upgradePtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  /// Whether the first selected unit can use tech_id now (researched, completed,
  /// not disabled; energy not checked).
  int bw_bridge_can_use_tech(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int tech_id,
  ) {
    return _bw_bridge_can_use_tech(bridge, owner, tech_id);
  }

  late final _bw_bridge_can_use_techPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_can_use_tech');
  late final _bw_bridge_can_use_tech = _bw_bridge_can_use_techPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  /// Casts a targeted ability (storm, lockdown, scanner sweep, ...) with the
  /// selection: issues the order whose tech is tech_id at (x, y) / target.
  bw_status bw_bridge_cast(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int tech_id,
    int x,
    int y,
    int target_unit_id,
    int queue,
  ) {
    return bw_status.fromValue(
      _bw_bridge_cast(bridge, owner, tech_id, x, y, target_unit_id, queue),
    );
  }

  late final _bw_bridge_castPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int32,
            ffi.Int,
          )
        >
      >('bw_bridge_cast');
  late final _bw_bridge_cast = _bw_bridge_castPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, int, int, int, int, int)
      >();

  bw_status bw_bridge_action(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int action,
  ) {
    return bw_status.fromValue(_bw_bridge_action(bridge, owner, action));
  }

  late final _bw_bridge_actionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int, ffi.Int)
        >
      >('bw_bridge_action');
  late final _bw_bridge_action = _bw_bridge_actionPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int)>();

  /// Sets the selected building's rally point to a position or a unit.
  bw_status bw_bridge_set_rally(
    ffi.Pointer<bw_bridge_t> bridge,
    int owner,
    int x,
    int y,
    int target_unit_id,
  ) {
    return bw_status.fromValue(
      _bw_bridge_set_rally(bridge, owner, x, y, target_unit_id),
    );
  }

  late final _bw_bridge_set_rallyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Int32,
          )
        >
      >('bw_bridge_set_rally');
  late final _bw_bridge_set_rally = _bw_bridge_set_rallyPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int, int, int, int)>();

  /// Loads a GRP from the MPQs (e.g. "unit\cmdbtns\cmdicons.grp"); returns a
  /// handle >= 0, or -1. Handles stay valid until the bridge is destroyed.
  int bw_bridge_grp_load(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> path,
  ) {
    return _bw_bridge_grp_load(bridge, path);
  }

  late final _bw_bridge_grp_loadPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
        >
      >('bw_bridge_grp_load');
  late final _bw_bridge_grp_load = _bw_bridge_grp_loadPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
      >();

  int bw_bridge_grp_frame_count(ffi.Pointer<bw_bridge_t> bridge, int handle) {
    return _bw_bridge_grp_frame_count(bridge, handle);
  }

  late final _bw_bridge_grp_frame_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_grp_frame_count');
  late final _bw_bridge_grp_frame_count = _bw_bridge_grp_frame_countPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  bw_status bw_bridge_grp_frame_size(
    ffi.Pointer<bw_bridge_t> bridge,
    int handle,
    int frame,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
  ) {
    return bw_status.fromValue(
      _bw_bridge_grp_frame_size(bridge, handle, frame, out_width, out_height),
    );
  }

  late final _bw_bridge_grp_frame_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_grp_frame_size');
  late final _bw_bridge_grp_frame_size = _bw_bridge_grp_frame_sizePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  /// width*height palette indices, 0 = transparent.
  bw_status bw_bridge_grp_decode(
    ffi.Pointer<bw_bridge_t> bridge,
    int handle,
    int frame,
    ffi.Pointer<ffi.Uint8> out_pixels,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_grp_decode(bridge, handle, frame, out_pixels, out_cap),
    );
  }

  late final _bw_bridge_grp_decodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_grp_decode');
  late final _bw_bridge_grp_decode = _bw_bridge_grp_decodePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  /// An 8-bit PCX image's pixels (palette indices). Pass out_pixels NULL to get
  /// the size only.
  bw_status bw_bridge_load_pcx(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> path,
    ffi.Pointer<ffi.Uint8> out_pixels,
    int out_cap,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
  ) {
    return bw_status.fromValue(
      _bw_bridge_load_pcx(
        bridge,
        path,
        out_pixels,
        out_cap,
        out_width,
        out_height,
      ),
    );
  }

  late final _bw_bridge_load_pcxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_load_pcx');
  late final _bw_bridge_load_pcx = _bw_bridge_load_pcxPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int>,
          ffi.Pointer<ffi.Int>,
        )
      >();

  /// Image type of the original's right-click target marker.
  int bw_bridge_cursor_marker_image() {
    return _bw_bridge_cursor_marker_image();
  }

  late final _bw_bridge_cursor_marker_imagePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>(
        'bw_bridge_cursor_marker_image',
      );
  late final _bw_bridge_cursor_marker_image = _bw_bridge_cursor_marker_imagePtr
      .asFunction<int Function()>();

  /// Selection circle image and its top-left map position for unit_id (for
  /// flashing a command target the way the original does).
  bw_status bw_bridge_get_selection_circle(
    ffi.Pointer<bw_bridge_t> bridge,
    int unit_id,
    ffi.Pointer<ffi.Int> out_image_type_id,
    ffi.Pointer<ffi.Int> out_x,
    ffi.Pointer<ffi.Int> out_y,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_selection_circle(
        bridge,
        unit_id,
        out_image_type_id,
        out_x,
        out_y,
      ),
    );
  }

  late final _bw_bridge_get_selection_circlePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int32,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_selection_circle');
  late final _bw_bridge_get_selection_circle =
      _bw_bridge_get_selection_circlePtr
          .asFunction<
            int Function(
              ffi.Pointer<bw_bridge_t>,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
            )
          >();

  int bw_bridge_sound_count(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_sound_count(bridge);
  }

  late final _bw_bridge_sound_countPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_sound_count',
      );
  late final _bw_bridge_sound_count = _bw_bridge_sound_countPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>)>();

  bw_status bw_bridge_get_sound_info(
    ffi.Pointer<bw_bridge_t> bridge,
    int sound_id,
    ffi.Pointer<bw_sound_info> out_info,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_sound_info(bridge, sound_id, out_info),
    );
  }

  late final _bw_bridge_get_sound_infoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<bw_sound_info>,
          )
        >
      >('bw_bridge_get_sound_info');
  late final _bw_bridge_get_sound_info = _bw_bridge_get_sound_infoPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, int, ffi.Pointer<bw_sound_info>)
      >();

  /// Copies the sound's WAV file into out_data. Pass out_data NULL to just get
  /// *out_len.
  bw_status bw_bridge_load_sound(
    ffi.Pointer<bw_bridge_t> bridge,
    int sound_id,
    ffi.Pointer<ffi.Uint8> out_data,
    int out_cap,
    ffi.Pointer<ffi.Int> out_len,
  ) {
    return bw_status.fromValue(
      _bw_bridge_load_sound(bridge, sound_id, out_data, out_cap, out_len),
    );
  }

  late final _bw_bridge_load_soundPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_load_sound');
  late final _bw_bridge_load_sound = _bw_bridge_load_soundPtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Int>,
        )
      >();

  /// Drains queued sound events (oldest first). Returns the count written.
  int bw_bridge_poll_sounds(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<bw_sound_event> out_events,
    int max_count,
  ) {
    return _bw_bridge_poll_sounds(bridge, out_events, max_count);
  }

  late final _bw_bridge_poll_soundsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<bw_sound_event>,
            ffi.Int,
          )
        >
      >('bw_bridge_poll_sounds');
  late final _bw_bridge_poll_sounds = _bw_bridge_poll_soundsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<bw_sound_event>, int)
      >();
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;
typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;

final class bw_bridge extends ffi.Opaque {}

typedef bw_bridge_t = bw_bridge;

/// Never a C++ exception crosses this boundary: every throwing OpenBW call is
/// caught internally and mapped to one of these.
enum bw_status {
  BW_OK(0),
  BW_ERR_ALREADY_LOADED(-1),
  BW_ERR_NOT_LOADED(-2),
  BW_ERR_ASSET_LOAD_FAILED(-3),
  BW_ERR_MAP_LOAD_FAILED(-4),
  BW_ERR_NO_GAME(-5),
  BW_ERR_INVALID_ARGUMENT(-6),

  /// the engine refused the command (requirements, placement, resources...)
  BW_ERR_REJECTED(-7),
  BW_ERR_UNKNOWN(-99);

  final int value;
  const bw_status(this.value);

  static bw_status fromValue(int value) => switch (value) {
    0 => BW_OK,
    -1 => BW_ERR_ALREADY_LOADED,
    -2 => BW_ERR_NOT_LOADED,
    -3 => BW_ERR_ASSET_LOAD_FAILED,
    -4 => BW_ERR_MAP_LOAD_FAILED,
    -5 => BW_ERR_NO_GAME,
    -6 => BW_ERR_INVALID_ARGUMENT,
    -7 => BW_ERR_REJECTED,
    -99 => BW_ERR_UNKNOWN,
    _ => throw ArgumentError('Unknown value for bw_status: $value'),
  };
}

final class bw_draw_item extends ffi.Struct {
  /// BW_DRAW_IMAGE or BW_DRAW_SELECTION_CIRCLE
  @ffi.Int32()
  external int kind;

  /// top-left of the frame, map pixels
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  @ffi.Int32()
  external int image_type_id;

  @ffi.Int32()
  external int frame_index;

  /// 0 or 1
  @ffi.Int32()
  external int flipped;

  /// player color (st.players[owner].color), row in bw_bridge_get_player_colors
  @ffi.Int32()
  external int color_index;

  /// player slot 0-11 (11 is neutral: minerals, geysers, critters)
  @ffi.Int32()
  external int owner;

  /// see BW_MOD_*; unknown values can be drawn as normal
  @ffi.Int32()
  external int modifier;

  /// for BW_MOD_GLOW: 1-based light table index
  @ffi.Int32()
  external int color_shift;

  /// owning unit, 0 if the sprite isn't a unit (effects, bullets...)
  @ffi.Int32()
  external int unit_id;

  /// selection circles only: hit points as 0-1000, -1 if not applicable
  @ffi.Int32()
  external int hp_permille;

  /// selection circles only: shields as 0-1000, -1 if none
  @ffi.Int32()
  external int shield_permille;
}

final class bw_unit_info extends ffi.Struct {
  @ffi.Int32()
  external int unit_id;

  @ffi.Int32()
  external int unit_type_id;

  @ffi.Int32()
  external int owner;

  /// sprite center, map pixels
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  /// BW_UNIT_FLAG_*
  @ffi.Int32()
  external int flags;

  /// whole hit points
  @ffi.Int32()
  external int hp;

  @ffi.Int32()
  external int max_hp;

  @ffi.Int32()
  external int shields;

  @ffi.Int32()
  external int max_shields;

  @ffi.Int32()
  external int energy;

  /// remaining minerals/gas for resource units
  @ffi.Int32()
  external int resources;

  /// unit_type dimensions (for selection boxes / minimap)
  @ffi.Int32()
  external int width;

  @ffi.Int32()
  external int height;

  /// build/train queue length (0-5)
  @ffi.Int32()
  external int queue_count;

  /// unit type ids in the queue
  @ffi.Array.multi([5])
  external ffi.Array<ffi.Int32> queue;

  /// progress of the current build/train (or own construction), -1 if none
  @ffi.Int32()
  external int progress_permille;

  @ffi.Int32()
  external int max_energy;

  /// tech id being researched, -1 if none
  @ffi.Int32()
  external int researching_tech;

  /// upgrade id being upgraded, -1 if none
  @ffi.Int32()
  external int upgrading;

  /// for researching_tech / upgrading, -1 if none
  @ffi.Int32()
  external int research_progress_permille;

  /// production buildings: 1 if a rally point is set
  @ffi.Int32()
  external int has_rally;

  /// rally point, map pixels
  @ffi.Int32()
  external int rally_x;

  @ffi.Int32()
  external int rally_y;

  /// unit the rally point follows, 0 if a position
  @ffi.Int32()
  external int rally_unit_id;
}

final class bw_unit_type_info extends ffi.Struct {
  @ffi.Int32()
  external int mineral_cost;

  @ffi.Int32()
  external int gas_cost;

  /// half units, like bw_bridge_supply
  @ffi.Int32()
  external int supply_required_raw;

  /// frames
  @ffi.Int32()
  external int build_time;

  /// pixels (multiple of 32 for buildings)
  @ffi.Int32()
  external int placement_width;

  @ffi.Int32()
  external int placement_height;

  @ffi.Int32()
  external int is_building;

  @ffi.Int32()
  external int is_addon;

  /// 0 zerg, 1 terran, 2 protoss, 3 other
  @ffi.Int32()
  external int race;

  /// from rez/stat_txt.tbl, UTF-8-safe ASCII
  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> name;

  /// Voice lines (sound ids, inclusive ranges; first > last means none),
  /// played by the host on selection (what), command (yes), repeated
  /// clicking (pissed) and completion (ready).
  @ffi.Int32()
  external int ready_sound;

  @ffi.Int32()
  external int what_first;

  @ffi.Int32()
  external int what_last;

  @ffi.Int32()
  external int pissed_first;

  @ffi.Int32()
  external int pissed_last;

  @ffi.Int32()
  external int yes_first;

  @ffi.Int32()
  external int yes_last;
}

/// --- Research, upgrades and abilities ------------------------------------------
final class bw_tech_info extends ffi.Struct {
  @ffi.Int32()
  external int mineral_cost;

  @ffi.Int32()
  external int gas_cost;

  /// frames
  @ffi.Int32()
  external int research_time;

  @ffi.Int32()
  external int energy_cost;

  /// frame in unit\cmdbtns\cmdicons.grp
  @ffi.Int32()
  external int icon;

  @ffi.Int32()
  external int race;

  /// for the owner passed in (or available without research)
  @ffi.Int32()
  external int researched;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;
}

final class bw_upgrade_info extends ffi.Struct {
  /// for the next level
  @ffi.Int32()
  external int mineral_cost;

  @ffi.Int32()
  external int gas_cost;

  /// frames, next level
  @ffi.Int32()
  external int time;

  @ffi.Int32()
  external int icon;

  @ffi.Int32()
  external int race;

  /// owner's current level
  @ffi.Int32()
  external int level;

  @ffi.Int32()
  external int max_level;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;
}

/// --- Sound -------------------------------------------------------------------
///
/// The simulation reports sounds (weapons, deaths, construction...) through
/// OpenBW's play_sound hook; they queue up here until polled. The host plays
/// them, using bw_sound_info and the reference UI's rules: volume from
/// min_volume and distance to the screen, priority-based channel stealing,
/// flags 0x10 = don't restart while playing, 0x02 = one at a time per unit type.
final class bw_sound_event extends ffi.Struct {
  @ffi.Int32()
  external int sound_id;

  /// 0 = not positional (play at min_volume)
  @ffi.Int32()
  external int has_position;

  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  /// source unit type, -1 if none
  @ffi.Int32()
  external int unit_type_id;
}

final class bw_sound_info extends ffi.Struct {
  @ffi.Int32()
  external int priority;

  @ffi.Int32()
  external int flags;

  /// 0-100
  @ffi.Int32()
  external int min_volume;

  /// relative to sound/ in the MPQs
  @ffi.Array.multi([80])
  external ffi.Array<ffi.Char> filename;
}

const int BW_BRIDGE_ABI_VERSION = 10;

const int BW_DRAW_IMAGE = 0;

const int BW_DRAW_SELECTION_CIRCLE = 1;

const int BW_MOD_NORMAL = 0;

const int BW_MOD_PLAYER_COLOR = 1;

const int BW_MOD_SHADOW = 10;

const int BW_MOD_GLOW = 9;

const int BW_UNIT_FLAG_BUILDING = 1;

const int BW_UNIT_FLAG_RESOURCE = 2;

const int BW_UNIT_FLAG_WORKER = 4;

const int BW_UNIT_FLAG_COMPLETED = 8;

const int BW_UNIT_FLAG_FLYER = 16;

const int BW_UNIT_FLAG_CAN_MOVE = 32;

const int BW_UNIT_FLAG_CLOAKED = 64;

const int BW_UNIT_FLAG_BURROWED = 128;

const int BW_UNIT_FLAG_STIMMED = 256;

const int BW_ORDER_DEFAULT = 0;

const int BW_ORDER_MOVE = 1;

const int BW_ORDER_ATTACK = 2;

const int BW_ORDER_STOP = 3;

const int BW_ORDER_HOLD = 4;

const int BW_ORDER_PATROL = 5;

const int BW_ORDER_RETURN_CARGO = 6;

const int BW_ORDER_REPAIR = 7;

const int BW_GROUP_ASSIGN = 0;

const int BW_GROUP_RECALL = 1;

const int BW_GROUP_ADD = 2;

const int BW_ACT_STIM = 0;

const int BW_ACT_SIEGE = 1;

const int BW_ACT_UNSIEGE = 2;

const int BW_ACT_CLOAK = 3;

const int BW_ACT_DECLOAK = 4;

const int BW_ACT_BURROW = 5;

const int BW_ACT_UNBURROW = 6;

const int BW_ACT_TRAIN_FIGHTER = 7;

const int BW_ACT_ARCHON_WARP = 8;

const int BW_ACT_DARK_ARCHON_MELD = 9;

const int BW_ACT_UNLOAD_ALL = 10;

const int BW_ACT_CANCEL_RESEARCH = 11;

const int BW_ACT_CANCEL_UPGRADE = 12;
