// GENERATED FILE — do not edit by hand.
// Source: engine/bridge/include/bw_bridge.h
// Regenerate with: dart run ffigen --config ffigen.yaml
// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Generated FFI bindings for the Brood War bridge (engine/bridge/include/bw_bridge.h).
class BwBridgeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  BwBridgeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  BwBridgeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int bw_bridge_abi_version() {
    return _bw_bridge_abi_version();
  }

  late final _bw_bridge_abi_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('bw_bridge_abi_version');
  late final _bw_bridge_abi_version = _bw_bridge_abi_versionPtr
      .asFunction<int Function()>();

  /// Create/destroy. One bw_bridge_t drives one simulation at a time.
  ffi.Pointer<bw_bridge_t> bw_bridge_create() {
    return _bw_bridge_create();
  }

  late final _bw_bridge_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<bw_bridge_t> Function()>>(
        'bw_bridge_create',
      );
  late final _bw_bridge_create = _bw_bridge_createPtr
      .asFunction<ffi.Pointer<bw_bridge_t> Function()>();

  void bw_bridge_destroy(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_destroy(bridge);
  }

  late final _bw_bridge_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_destroy',
      );
  late final _bw_bridge_destroy = _bw_bridge_destroyPtr
      .asFunction<void Function(ffi.Pointer<bw_bridge_t>)>();

  /// Loads StarDat.mpq/BrooDat.mpq/Patch_rt.mpq from data_dir (must end in a
  /// path separator or not — both are accepted). This is the "bring your own
  /// assets" entry point: data_dir must be a user-supplied location, never a
  /// path inside the app bundle. See docs/third_party_licensing.md.
  bw_status bw_bridge_load_assets(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> data_dir,
  ) {
    return bw_status.fromValue(_bw_bridge_load_assets(bridge, data_dir));
  }

  late final _bw_bridge_load_assetsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
        >
      >('bw_bridge_load_assets');
  late final _bw_bridge_load_assets = _bw_bridge_load_assetsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>)
      >();

  /// Starts a single-player melee game on the given map: `my_player` occupies
  /// slot my_player_slot (0-11) with race my_race (0=zerg,1=terran,2=protoss,
  /// per bwgame.h's race_t ordinal — kept as a plain int here, not an enum, so
  /// this header has no dependency on OpenBW's own enum layout). All other
  /// slots are inactive. This matches the minimal setup already proven by
  /// engine/tools/sim_smoke_test; multiplayer/AI opponents are a later revision.
  bw_status bw_bridge_new_melee_game(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Char> map_file,
    int my_player_slot,
    int my_race,
  ) {
    return bw_status.fromValue(
      _bw_bridge_new_melee_game(bridge, map_file, my_player_slot, my_race),
    );
  }

  late final _bw_bridge_new_melee_gamePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Char>,
            ffi.Int,
            ffi.Int,
          )
        >
      >('bw_bridge_new_melee_game');
  late final _bw_bridge_new_melee_game = _bw_bridge_new_melee_gamePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Char>, int, int)
      >();

  /// Advances the simulation by n_frames (synchronous, blocking).
  bw_status bw_bridge_step(ffi.Pointer<bw_bridge_t> bridge, int n_frames) {
    return bw_status.fromValue(_bw_bridge_step(bridge, n_frames));
  }

  late final _bw_bridge_stepPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_step');
  late final _bw_bridge_step = _bw_bridge_stepPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  /// Scalar queries, valid only after bw_bridge_new_melee_game succeeded.
  int bw_bridge_current_frame(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_current_frame(bridge);
  }

  late final _bw_bridge_current_framePtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_current_frame',
      );
  late final _bw_bridge_current_frame = _bw_bridge_current_framePtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>)>();

  int bw_bridge_unit_count(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_unit_count(bridge, player_slot);
  }

  late final _bw_bridge_unit_countPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_unit_count');
  late final _bw_bridge_unit_count = _bw_bridge_unit_countPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  int bw_bridge_minerals(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_minerals(bridge, player_slot);
  }

  late final _bw_bridge_mineralsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_minerals');
  late final _bw_bridge_minerals = _bw_bridge_mineralsPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  int bw_bridge_gas(ffi.Pointer<bw_bridge_t> bridge, int player_slot) {
    return _bw_bridge_gas(bridge, player_slot);
  }

  late final _bw_bridge_gasPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>, ffi.Int)>
      >('bw_bridge_gas');
  late final _bw_bridge_gas = _bw_bridge_gasPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>, int)>();

  /// Fills out_sprites (capacity max_count) with every currently visible
  /// image across all players, returns the number written (which may be less
  /// than the true total if max_count was too small — call again with a
  /// larger buffer if the return value equals max_count).
  /// v0 does not filter by fog-of-war/visibility for a specific viewer; that
  /// is a known gap, not yet implemented.
  int bw_bridge_get_visible_sprites(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<bw_sprite_info> out_sprites,
    int max_count,
  ) {
    return _bw_bridge_get_visible_sprites(bridge, out_sprites, max_count);
  }

  late final _bw_bridge_get_visible_spritesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<bw_sprite_info>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_visible_sprites');
  late final _bw_bridge_get_visible_sprites = _bw_bridge_get_visible_spritesPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<bw_sprite_info>, int)
      >();

  /// The tileset index (0-7) of the currently loaded map, used to pick which
  /// Tileset/<name>.wpe palette and recolor table apply.
  int bw_bridge_get_tileset_index(ffi.Pointer<bw_bridge_t> bridge) {
    return _bw_bridge_get_tileset_index(bridge);
  }

  late final _bw_bridge_get_tileset_indexPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<bw_bridge_t>)>>(
        'bw_bridge_get_tileset_index',
      );
  late final _bw_bridge_get_tileset_index = _bw_bridge_get_tileset_indexPtr
      .asFunction<int Function(ffi.Pointer<bw_bridge_t>)>();

  /// 256 RGBA8888 entries (1024 bytes) — the one palette every decoded pixel
  /// index below should be looked up against. out_cap must be >= 1024.
  bw_status bw_bridge_get_palette(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Uint8> out_rgba,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_palette(bridge, out_rgba, out_cap),
    );
  }

  late final _bw_bridge_get_palettePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_palette');
  late final _bw_bridge_get_palette = _bw_bridge_get_palettePtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// 16 players x 8 shades (128 bytes) — palette indices 8..15 in a decoded
  /// sprite frame should be remapped through player_colors[owner] before
  /// looking up the palette, to recolor a unit for its owner. out_cap must be
  /// >= 128.
  bw_status bw_bridge_get_player_colors(
    ffi.Pointer<bw_bridge_t> bridge,
    ffi.Pointer<ffi.Uint8> out_colors,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_player_colors(bridge, out_colors, out_cap),
    );
  }

  late final _bw_bridge_get_player_colorsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_get_player_colors');
  late final _bw_bridge_get_player_colors = _bw_bridge_get_player_colorsPtr
      .asFunction<
        int Function(ffi.Pointer<bw_bridge_t>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Frame dimensions for a given image type's frame, needed to size the
  /// buffer passed to bw_bridge_decode_image_frame.
  bw_status bw_bridge_get_image_frame_size(
    ffi.Pointer<bw_bridge_t> bridge,
    int image_type_id,
    int frame_index,
    ffi.Pointer<ffi.Int> out_width,
    ffi.Pointer<ffi.Int> out_height,
  ) {
    return bw_status.fromValue(
      _bw_bridge_get_image_frame_size(
        bridge,
        image_type_id,
        frame_index,
        out_width,
        out_height,
      ),
    );
  }

  late final _bw_bridge_get_image_frame_sizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Int>,
            ffi.Pointer<ffi.Int>,
          )
        >
      >('bw_bridge_get_image_frame_size');
  late final _bw_bridge_get_image_frame_size =
      _bw_bridge_get_image_frame_sizePtr
          .asFunction<
            int Function(
              ffi.Pointer<bw_bridge_t>,
              int,
              int,
              ffi.Pointer<ffi.Int>,
              ffi.Pointer<ffi.Int>,
            )
          >();

  /// Decodes one GRP frame into out_pixels as width*height palette-index bytes
  /// (0-255, use bw_bridge_get_palette to turn these into colors; index 0 is
  /// BW's transparent index). out_cap must be >= width*height from
  /// bw_bridge_get_image_frame_size. Does not apply player-color recoloring —
  /// that is a host-side lookup against bw_bridge_get_player_colors, since it
  /// depends on which player owns the sprite being drawn, not the image data
  /// itself.
  bw_status bw_bridge_decode_image_frame(
    ffi.Pointer<bw_bridge_t> bridge,
    int image_type_id,
    int frame_index,
    int flipped,
    ffi.Pointer<ffi.Uint8> out_pixels,
    int out_cap,
  ) {
    return bw_status.fromValue(
      _bw_bridge_decode_image_frame(
        bridge,
        image_type_id,
        frame_index,
        flipped,
        out_pixels,
        out_cap,
      ),
    );
  }

  late final _bw_bridge_decode_image_framePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<bw_bridge_t>,
            ffi.Int,
            ffi.Int,
            ffi.Int,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('bw_bridge_decode_image_frame');
  late final _bw_bridge_decode_image_frame = _bw_bridge_decode_image_framePtr
      .asFunction<
        int Function(
          ffi.Pointer<bw_bridge_t>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();
}

typedef __u_char = ffi.UnsignedChar;
typedef Dart__u_char = int;
typedef __u_short = ffi.UnsignedShort;
typedef Dart__u_short = int;
typedef __u_int = ffi.UnsignedInt;
typedef Dart__u_int = int;
typedef __u_long = ffi.UnsignedLong;
typedef Dart__u_long = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __int64_t = ffi.Long;
typedef Dart__int64_t = int;
typedef __uint64_t = ffi.UnsignedLong;
typedef Dart__uint64_t = int;
typedef __int_least8_t = __int8_t;
typedef __uint_least8_t = __uint8_t;
typedef __int_least16_t = __int16_t;
typedef __uint_least16_t = __uint16_t;
typedef __int_least32_t = __int32_t;
typedef __uint_least32_t = __uint32_t;
typedef __int_least64_t = __int64_t;
typedef __uint_least64_t = __uint64_t;
typedef __quad_t = ffi.Long;
typedef Dart__quad_t = int;
typedef __u_quad_t = ffi.UnsignedLong;
typedef Dart__u_quad_t = int;
typedef __intmax_t = ffi.Long;
typedef Dart__intmax_t = int;
typedef __uintmax_t = ffi.UnsignedLong;
typedef Dart__uintmax_t = int;
typedef __dev_t = ffi.UnsignedLong;
typedef Dart__dev_t = int;
typedef __uid_t = ffi.UnsignedInt;
typedef Dart__uid_t = int;
typedef __gid_t = ffi.UnsignedInt;
typedef Dart__gid_t = int;
typedef __ino_t = ffi.UnsignedLong;
typedef Dart__ino_t = int;
typedef __ino64_t = ffi.UnsignedLong;
typedef Dart__ino64_t = int;
typedef __mode_t = ffi.UnsignedInt;
typedef Dart__mode_t = int;
typedef __nlink_t = ffi.UnsignedLong;
typedef Dart__nlink_t = int;
typedef __off_t = ffi.Long;
typedef Dart__off_t = int;
typedef __off64_t = ffi.Long;
typedef Dart__off64_t = int;
typedef __pid_t = ffi.Int;
typedef Dart__pid_t = int;
typedef __clock_t = ffi.Long;
typedef Dart__clock_t = int;
typedef __rlim_t = ffi.UnsignedLong;
typedef Dart__rlim_t = int;
typedef __rlim64_t = ffi.UnsignedLong;
typedef Dart__rlim64_t = int;
typedef __id_t = ffi.UnsignedInt;
typedef Dart__id_t = int;
typedef __time_t = ffi.Long;
typedef Dart__time_t = int;
typedef __useconds_t = ffi.UnsignedInt;
typedef Dart__useconds_t = int;
typedef __suseconds_t = ffi.Long;
typedef Dart__suseconds_t = int;
typedef __suseconds64_t = ffi.Long;
typedef Dart__suseconds64_t = int;
typedef __daddr_t = ffi.Int;
typedef Dart__daddr_t = int;
typedef __key_t = ffi.Int;
typedef Dart__key_t = int;
typedef __clockid_t = ffi.Int;
typedef Dart__clockid_t = int;
typedef __timer_t = ffi.Pointer<ffi.Void>;
typedef __blksize_t = ffi.Long;
typedef Dart__blksize_t = int;
typedef __blkcnt_t = ffi.Long;
typedef Dart__blkcnt_t = int;
typedef __blkcnt64_t = ffi.Long;
typedef Dart__blkcnt64_t = int;
typedef __fsblkcnt_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt_t = int;
typedef __fsblkcnt64_t = ffi.UnsignedLong;
typedef Dart__fsblkcnt64_t = int;
typedef __fsfilcnt_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt_t = int;
typedef __fsfilcnt64_t = ffi.UnsignedLong;
typedef Dart__fsfilcnt64_t = int;
typedef __fsword_t = ffi.Long;
typedef Dart__fsword_t = int;
typedef __ssize_t = ffi.Long;
typedef Dart__ssize_t = int;
typedef __syscall_slong_t = ffi.Long;
typedef Dart__syscall_slong_t = int;
typedef __syscall_ulong_t = ffi.UnsignedLong;
typedef Dart__syscall_ulong_t = int;
typedef __loff_t = __off64_t;
typedef __caddr_t = ffi.Pointer<ffi.Char>;
typedef __intptr_t = ffi.Long;
typedef Dart__intptr_t = int;
typedef __socklen_t = ffi.UnsignedInt;
typedef Dart__socklen_t = int;
typedef __sig_atomic_t = ffi.Int;
typedef Dart__sig_atomic_t = int;
typedef int_least8_t = __int_least8_t;
typedef int_least16_t = __int_least16_t;
typedef int_least32_t = __int_least32_t;
typedef int_least64_t = __int_least64_t;
typedef uint_least8_t = __uint_least8_t;
typedef uint_least16_t = __uint_least16_t;
typedef uint_least32_t = __uint_least32_t;
typedef uint_least64_t = __uint_least64_t;
typedef int_fast8_t = ffi.SignedChar;
typedef Dartint_fast8_t = int;
typedef int_fast16_t = ffi.Long;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Long;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Long;
typedef Dartint_fast64_t = int;
typedef uint_fast8_t = ffi.UnsignedChar;
typedef Dartuint_fast8_t = int;
typedef uint_fast16_t = ffi.UnsignedLong;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.UnsignedLong;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.UnsignedLong;
typedef Dartuint_fast64_t = int;
typedef intmax_t = __intmax_t;
typedef uintmax_t = __uintmax_t;

final class bw_bridge extends ffi.Opaque {}

typedef bw_bridge_t = bw_bridge;

/// Status codes returned by functions below. Never a C++ exception crosses
/// this boundary — every throwing OpenBW call is caught internally and
/// mapped to one of these.
enum bw_status {
  BW_OK(0),
  BW_ERR_ALREADY_LOADED(-1),
  BW_ERR_NOT_LOADED(-2),
  BW_ERR_ASSET_LOAD_FAILED(-3),
  BW_ERR_MAP_LOAD_FAILED(-4),
  BW_ERR_NO_GAME(-5),
  BW_ERR_INVALID_ARGUMENT(-6),
  BW_ERR_UNKNOWN(-99);

  final int value;
  const bw_status(this.value);

  static bw_status fromValue(int value) => switch (value) {
    0 => BW_OK,
    -1 => BW_ERR_ALREADY_LOADED,
    -2 => BW_ERR_NOT_LOADED,
    -3 => BW_ERR_ASSET_LOAD_FAILED,
    -4 => BW_ERR_MAP_LOAD_FAILED,
    -5 => BW_ERR_NO_GAME,
    -6 => BW_ERR_INVALID_ARGUMENT,
    -99 => BW_ERR_UNKNOWN,
    _ => throw ArgumentError('Unknown value for bw_status: $value'),
  };
}

/// Fixed-layout struct shared across the FFI/WASM boundary — do not reorder
/// or change field widths without bumping BW_BRIDGE_ABI_VERSION.
final class bw_sprite_info extends ffi.Struct {
  /// map pixel position
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  /// identifies which GRP + recolor rules to use
  @ffi.Int32()
  external int image_type_id;

  @ffi.Int32()
  external int frame_index;

  /// 0 or 1 (horizontal flip)
  @ffi.Int32()
  external int flipped;

  /// player slot 0-11, for recoloring
  @ffi.Int32()
  external int owner;

  /// z-order
  @ffi.Int32()
  external int elevation_level;

  /// image->modifier (0/1 = normal/player-color; others are cloak/shadow/warp/etc, see bw_render_util.h — approximate or ignore these for now)
  @ffi.Int32()
  external int modifier;
}

const int BW_BRIDGE_ABI_VERSION = 2;
