#!/usr/bin/env python3
# tool/gen_bridge_raw.py
#
# Generates the raw call layer between Dart and the C bridge from
# engine/bridge/include/bw_bridge.h, for both targets:
#   lib/engine/bridge_raw.dart      abstract class: one method per C function,
#                                   integers in and out (pointers are addresses)
#   lib/engine/bridge_raw_ffi.dart  dart:ffi implementation (desktop, Android)
#   lib/engine/bridge_raw_web.dart  WebAssembly implementation (browser)
#
# Run after changing bw_bridge.h:  python3 tool/gen_bridge_raw.py

import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = ROOT / 'engine/bridge/include/bw_bridge.h'

text = HEADER.read_text()
# Strip comments.
text = re.sub(r'//[^\n]*', '', text)
text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
protos = re.findall(r'([A-Za-z_][\w \t\*]*?)\b(bw_bridge_\w+)\s*\(([^)]*)\)\s*;', text, flags=re.S)

def kind(ctype):
    t = ' '.join(ctype.split())
    if '*' in t:
        return 'ptr'
    if t == 'void':
        return 'void'
    if t in ('uint32_t',):
        return 'u32'
    if t in ('int', 'int32_t', 'bw_status'):
        return 'i32'
    raise SystemExit(f'unhandled C type: {t!r}')

funcs = []
for ret, name, params in protos:
    ret = ret.strip()
    args = []
    params = params.strip()
    if params and params != 'void':
        for p in params.split(','):
            p = ' '.join(p.split())
            m = re.match(r'(.*?)(\w+)$', p)
            ctype, pname = m.group(1).strip(), m.group(2)
            args.append((kind(ctype), pname))
    funcs.append((kind(ret), name, args))

HEADER_NOTE = '// GENERATED by tool/gen_bridge_raw.py from engine/bridge/include/bw_bridge.h. Do not edit.\n// ignore_for_file: non_constant_identifier_names, constant_identifier_names\n'

# --- abstract ---------------------------------------------------------------
out = [HEADER_NOTE, '''
// The C bridge, call by call: integers in and out, pointers as addresses in
// the engine's memory. lib/engine/bw_engine.dart builds the real API on it.

import 'dart:typed_data';

abstract class BridgeRaw {
  /// Engine memory: allocate, free, and view bytes (little-endian).
  int malloc(int size);
  void free(int address);
  Uint8List bytes(int address, int length);
  ByteData data(int address, int length) => ByteData.sublistView(bytes(address, length));

  /// Replays a saved command log (see bw_bridge_replay_commands); off the UI
  /// thread where the platform allows it.
  Future<int> replayCommands(int bridge, Int32List log, int endFrame);

''']
defines = re.findall(r'#define[ \t]+(BW_\w+)[ \t]+(-?\d+)', HEADER.read_text())
consts = ''.join(f'const int {n} = {v};\n' for n, v in defines)
out[1] = out[1].replace('abstract class BridgeRaw {', consts + '\nabstract class BridgeRaw {', 1)
for ret, name, args in funcs:
    sig = ', '.join(f'int {a}' for _, a in args)
    rt = 'void' if ret == 'void' else 'int'
    out.append(f'  {rt} {name}({sig});\n')
out.append('}\n')
(ROOT / 'lib/engine/bridge_raw.dart').write_text(''.join(out))

# --- ffi ---------------------------------------------------------------------
NT = {'i32': 'ffi.Int32', 'u32': 'ffi.Uint32', 'ptr': 'ffi.IntPtr', 'void': 'ffi.Void'}
out = [HEADER_NOTE, '''
// dart:ffi implementation of BridgeRaw (Linux desktop now, Android later).

import 'dart:ffi' as ffi;
import 'dart:io';
import 'dart:isolate';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

import 'bridge_raw.dart';

class BridgeRawFfi extends BridgeRaw {
  final String libraryPath;
  final ffi.DynamicLibrary _lib;

  BridgeRawFfi(this.libraryPath) : _lib = ffi.DynamicLibrary.open(libraryPath);

  /// Next to the executable when bundled (linux/CMakeLists.txt installs it
  /// into the bundle's lib/), otherwise the bridge's own build output.
  static String defaultLibraryPath() {
    final exeDir = File(Platform.resolvedExecutable).parent.path;
    final bundled = '$exeDir/lib/libbwbridge.so';
    if (File(bundled).existsSync()) return bundled;
    return '${Directory.current.path}/engine/bridge/build/libbwbridge.so';
  }

  @override
  int malloc(int size) => calloc<ffi.Uint8>(size <= 0 ? 1 : size).address;

  @override
  void free(int address) => calloc.free(ffi.Pointer<ffi.Uint8>.fromAddress(address));

  @override
  Uint8List bytes(int address, int length) => ffi.Pointer<ffi.Uint8>.fromAddress(address).asTypedList(length);

  @override
  Future<int> replayCommands(int bridge, Int32List log, int endFrame) {
    final path = libraryPath;
    return Isolate.run(() {
      final raw = BridgeRawFfi(path);
      final buf = raw.malloc(log.isEmpty ? 4 : log.lengthInBytes);
      try {
        raw.bytes(buf, log.lengthInBytes).setAll(0, log.buffer.asUint8List(log.offsetInBytes, log.lengthInBytes));
        return raw.bw_bridge_replay_commands(bridge, buf, log.length, endFrame);
      } finally {
        raw.free(buf);
      }
    });
  }

''']
for ret, name, args in funcs:
    native_args = ', '.join(NT[k] for k, _ in args)
    dart_args = ', '.join('int' for _ in args)
    rt_native = NT[ret]
    rt_dart = 'void' if ret == 'void' else 'int'
    out.append(f'  late final _{name} = _lib.lookupFunction<{rt_native} Function({native_args}), {rt_dart} Function({dart_args})>(\'{name}\');\n')
    sig = ', '.join(f'int {a}' for _, a in args)
    call = ', '.join(a for _, a in args)
    if ret == 'void':
        out.append(f'  @override\n  void {name}({sig}) => _{name}({call});\n\n')
    else:
        out.append(f'  @override\n  int {name}({sig}) => _{name}({call});\n\n')
out.append('}\n')
(ROOT / 'lib/engine/bridge_raw_ffi.dart').write_text(''.join(out))

# --- web ---------------------------------------------------------------------
out = [HEADER_NOTE, '''
// WebAssembly implementation of BridgeRaw: the bridge compiled by
// engine/web/build_wasm.sh (web/bwbridge.js + .wasm), created through the
// Emscripten module factory `createBwBridge` that web/index.html loads.

import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'dart:typed_data';

import 'bridge_raw.dart';

@JS('createBwBridge')
external JSPromise<JSObject> _createBwBridge();

class BridgeRawWeb extends BridgeRaw {
  final JSObject module;
  BridgeRawWeb._(this.module);

  static BridgeRawWeb? _instance;

  /// The engine module is created once per page and shared by every game,
  /// so the game data written into its file system stays there.
  static Future<BridgeRawWeb> open() async {
    return _instance ??= BridgeRawWeb._(await _createBwBridge().toDart);
  }

  int _call(String name, List<int> args) {
    final r = module.callMethodVarArgs<JSAny?>(name.toJS, [for (final a in args) a.toJS]);
    return r == null || r.isUndefinedOrNull ? 0 : (r as JSNumber).toDartInt;
  }

  JSUint8Array get _heap => module.getProperty<JSUint8Array>('HEAPU8'.toJS);

  @override
  int malloc(int size) {
    final p = _call('_malloc', [size <= 0 ? 1 : size]);
    bytes(p, size <= 0 ? 1 : size).fillRange(0, size <= 0 ? 1 : size, 0);
    return p;
  }

  @override
  void free(int address) => _call('_free', [address]);

  // The heap can grow (and be replaced), so always take a fresh view.
  @override
  Uint8List bytes(int address, int length) => _heap.toDart.buffer.asUint8List(address, length);

  @override
  Future<int> replayCommands(int bridge, Int32List log, int endFrame) async {
    final buf = malloc(log.isEmpty ? 4 : log.lengthInBytes);
    try {
      bytes(buf, log.lengthInBytes).setAll(0, log.buffer.asUint8List(log.offsetInBytes, log.lengthInBytes));
      return bw_bridge_replay_commands(bridge, buf, log.length, endFrame);
    } finally {
      free(buf);
    }
  }

  /// Emscripten's file system, where the game data lives (MEMFS).
  JSObject get fs => module.getProperty<JSObject>('FS'.toJS);

''']
for ret, name, args in funcs:
    sig = ', '.join(f'int {a}' for _, a in args)
    call = ', '.join(a for _, a in args)
    if ret == 'void':
        out.append(f'  @override\n  void {name}({sig}) => _call(\'_{name}\', [{call}]);\n\n')
    elif ret == 'u32':
        out.append(f'  @override\n  int {name}({sig}) => _call(\'_{name}\', [{call}]) & 0xffffffff;\n\n')
    else:
        out.append(f'  @override\n  int {name}({sig}) => _call(\'_{name}\', [{call}]);\n\n')
out.append('}\n')
(ROOT / 'lib/engine/bridge_raw_web.dart').write_text(''.join(out))

# For the build script: the functions to export from WebAssembly.
(ROOT / 'engine/web/exported_functions.txt').write_text(
    ','.join(['_malloc', '_free'] + [f'_{n}' for _, n, _ in funcs]) + '\n')
print(f'{len(funcs)} functions')
