#!/usr/bin/env python3
# tool/gen_bot_names.py
#
# Generates engine/bridge/src/botscript_names.h from OpenBW's bwenums.h: the
# names bot profiles use for unit types, techs and upgrades (the enum names
# in lower case, "terran_marine", "stim_packs", "u_238_shells").
#
# Run after updating OpenBW:  python3 tool/gen_bot_names.py

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
text = (ROOT / 'engine/vendor/openbw/bwenums.h').read_text()


def names(enum):
    body = re.search(r'enum struct ' + enum + r' : int \{(.*?)\};', text, flags=re.S).group(1)
    out = []
    for line in body.split(','):
        line = re.sub(r'//[^\n]*', '', line).strip()
        if not line:
            continue
        name = line.split('=')[0].strip()
        if name == 'None':
            break
        out.append(name.lower())
    return out


units, techs, upgrades = names('UnitTypes'), names('TechTypes'), names('UpgradeTypes')
# A tech and an upgrade of the same name would be ambiguous in a research row.
assert not set(techs) & set(upgrades), set(techs) & set(upgrades)
assert not set(units) & (set(techs) | set(upgrades))


def table(name, items):
    rows = ''.join(f'\t"{n}",\n' for n in items)
    return f'static const char* const {name}[] = {{\n{rows}}};\nstatic const int {name}_count = {len(items)};\n\n'


out = ('// GENERATED by tool/gen_bot_names.py from engine/vendor/openbw/bwenums.h. Do not edit.\n'
       '// Names bot profiles use, in enum order (index = UnitTypes, TechTypes, UpgradeTypes value).\n\n'
       '#ifndef BOTSCRIPT_NAMES_H\n#define BOTSCRIPT_NAMES_H\n\nnamespace botscript {\n\n'
       + table('unit_names', units) + table('tech_names', techs) + table('upgrade_names', upgrades)
       + '} // namespace botscript\n\n#endif // BOTSCRIPT_NAMES_H\n')
(ROOT / 'engine/bridge/src/botscript_names.h').write_text(out)
print(len(units), len(techs), len(upgrades))
